$axure.loadCurrentPage({
  "url":"color_picker1_internal.html",
  "generationDate":new Date(1594040141853.95),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"e9ab6304b1074ebfad932f2114e53a04",
    "type":"Axure:Page",
    "name":"color_picker1_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ee8178f1eec4f04b33258c2b3c6c169",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":173,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ef81e2223a4650a0095388d922f573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":173,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/color_picker1_internal/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6ee8178f1eec4f04b33258c2b3c6c169":{
      "scriptId":"u0"},
    "91ef81e2223a4650a0095388d922f573":{
      "scriptId":"u1"}}});