$axure.loadCurrentPage({
  "url":"e3_view.html",
  "generationDate":new Date(1594037917711.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7b3475574dc14c5b887c5258ac193c4b",
    "type":"Axure:Page",
    "name":"E3_view",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bb50ee87bb2d43549880f208b83203c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1360,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd6daedaa8ad4144af8956d7822463bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1360,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u0.png"}},
{
          "id":"2469b9a540da4e06a70f815a63276a82",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":132},
            "size":{
              "width":1360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/e3_view/u2_line.png"}},
{
          "id":"b2fd36c2ff804b379998a90a20a875fc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":171},
            "size":{
              "width":1360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/e3_view/u2_line.png"}},
{
          "id":"2cd90be7c2ef4264a603deb5500f413f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F0F0},
            "location":{
              "x":0,
              "y":138},
            "size":{
              "width":1360,
              "height":38},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"281f26279b584498b404aed90bb127cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F0F0},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":1360,
                  "height":38},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u4.png"}},
{
          "id":"c967d80299ff47bca222b24e1ce69d00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":26,
              "y":146},
            "size":{
              "width":152,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f61ee6a41645909bbae27988e5fc26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":146},
                "size":{
                  "width":152,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"045d3e190fad409f8b36e0fc32d0e2f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":28,
              "y":200},
            "size":{
              "width":30,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d048da6f93442d0901d1d660468ee39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":200},
                "size":{
                  "width":30,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b99570c262ad4ed09a67e1c1df3eb2fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":137,
              "y":200},
            "size":{
              "width":31,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae3547df529478eab3d9c4f0a1f1b65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":137,
                  "y":200},
                "size":{
                  "width":31,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10bc4aed2e134eeb98bc1b43a98c9296",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":257,
              "y":200},
            "size":{
              "width":26,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d0228f9a8ca4760a3360ee0ad9cd70a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":257,
                  "y":200},
                "size":{
                  "width":26,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c6f1e500a344513ac40bb1584296fe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":372,
              "y":200},
            "size":{
              "width":25,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f509fe30dfba4b0388597b33e9aa1ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":372,
                  "y":200},
                "size":{
                  "width":25,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9daa70d62ecb4623b1b9b2583a9b9f42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":486,
              "y":200},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ffa800ada44804b927f348cd9ee9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":486,
                  "y":200},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38f816cf56df4784afe39974c4d36d5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":608,
              "y":200},
            "size":{
              "width":22,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7de25a752594f4eb7a3abdeb3593b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":608,
                  "y":200},
                "size":{
                  "width":22,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39400b45aae942e59706279e6e03ee0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":720,
              "y":200},
            "size":{
              "width":31,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a00663d05264ca6979f42d2c6210f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":720,
                  "y":200},
                "size":{
                  "width":31,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ef5721ee42e477dba7e5ceeef161a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":841,
              "y":200},
            "size":{
              "width":23,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d8a7e5b50d4211b1bfabb19943d406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":841,
                  "y":200},
                "size":{
                  "width":23,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c3555b1cb3e4fd58e4a3fa372a02da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFDD00},
            "location":{
              "x":92,
              "y":228},
            "size":{
              "width":120,
              "height":4},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec3bdeec015a4b52a464e83ef29d94db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFDD00},
                "location":{
                  "x":92,
                  "y":228},
                "size":{
                  "width":120,
                  "height":4},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u24.png"}},
{
          "id":"796a5a67216b41398c3278a4052d2649",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":28,
              "y":260},
            "size":{
              "width":112,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f6cc03f3f74c7f8f6ee87a85241e5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":260},
                "size":{
                  "width":112,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67bee50cf61346d3a02094d93b230162",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":28,
              "y":294},
            "size":{
              "width":212,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba3c2c3b23294eae82fb441d4f1322e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":294},
                "size":{
                  "width":212,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c60e0bdf5f8427290b019d627eccebd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":28,
              "y":750},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"695c83c77bcb422eb57f6553bebd75aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":750},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef1c62d14b2e420f8721142915533cb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":243,
              "y":304},
            "size":{
              "width":10,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96b814f94a1947999fbcb0731015102f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":243,
                  "y":304},
                "size":{
                  "width":10,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u32.png"}},
{
          "id":"9fd157a8998d4b258d89fb7208ee2695",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":128,
              "y":760},
            "size":{
              "width":10,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7769497ed0947dab1adf252b923c4f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":128,
                  "y":760},
                "size":{
                  "width":10,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u34.png"}},
{
          "id":"2d89e974553f4e6aa729d700079663bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF003366,
              "opacity":1},
            "location":{
              "x":28,
              "y":800},
            "size":{
              "width":232,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9313045370c44ddaaa0f799f9cd018b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF003366,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":800},
                "size":{
                  "width":232,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fbaa9ddd59a4ec88dc743139634ccd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":28,
              "y":834},
            "size":{
              "width":162,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"845c3d67fa0949f1bdd1b9ca434f2897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":834},
                "size":{
                  "width":162,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5486334b29ef49b4a0fe9e1845d5d989",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":28,
              "y":865},
            "size":{
              "width":238,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dbc7a30a99d4c5db396608ef2e797ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":865},
                "size":{
                  "width":238,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ed0212273274b80ae06669c5157d60f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":191,
              "y":844},
            "size":{
              "width":10,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13b869a1d5174440965586e533ff03b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":191,
                  "y":844},
                "size":{
                  "width":10,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u34.png"}},
{
          "id":"5190d10674d64f9da97636affaa4df0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":266,
              "y":875},
            "size":{
              "width":10,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37c92bc1afb145a88c7c2f5c89ceb7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":266,
                  "y":875},
                "size":{
                  "width":10,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u34.png"}},
{
          "id":"58ba3ccbac58412c9354c54ae3afe8fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":28,
              "y":896},
            "size":{
              "width":162,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae7c181922b4e168774b18ce333799f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":896},
                "size":{
                  "width":162,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"761509eb626b4f528c24981871cd5a9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":28,
              "y":927},
            "size":{
              "width":238,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b88f9793b9343b1b8df047224cd4029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":927},
                "size":{
                  "width":238,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29e104eeacb644a780a07806f2ce0ce8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":183,
              "y":906},
            "size":{
              "width":10,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb4a9feabff4881ac1efda96e735cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":183,
                  "y":906},
                "size":{
                  "width":10,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u34.png"}},
{
          "id":"8082f7ed26af46248499654a78a90905",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":245,
              "y":937},
            "size":{
              "width":10,
              "height":5}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a0bb1ef63a4b11802e6686289f7c23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":245,
                  "y":937},
                "size":{
                  "width":10,
                  "height":5}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u32.png"}},
{
          "id":"dbcaf4148478433bbaccd2c988c03b67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":28,
              "y":927},
            "size":{
              "width":598,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1668aaaab7014cd28c6253cfb7ede7c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":28,
                  "y":927},
                "size":{
                  "width":598,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u54.png"}},
{
          "id":"718b748715704d458304065bb0fbd02d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":325},
            "size":{
              "width":1322,
              "height":360}},
          "adaptiveStyles":{
},
          "scrollbars":"horizontalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1cc11be8858446eb93ed219fcf4dbb30",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d8cb3442133f4311b84f049ae9d12ff3",
                  "label":"",
                  "parentDynamicPanel":"718b748715704d458304065bb0fbd02d",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1800,
                      "height":340}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"ccc0c029eb544effb002de5040005181",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":28,
              "y":696},
            "size":{
              "width":244,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6067b29a91bb4fedb3cf78f579fe943e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":28,
                  "y":696},
                "size":{
                  "width":244,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u58.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bb50ee87bb2d43549880f208b83203c9":{
      "scriptId":"u0"},
    "cd6daedaa8ad4144af8956d7822463bb":{
      "scriptId":"u1"},
    "2469b9a540da4e06a70f815a63276a82":{
      "scriptId":"u2"},
    "b2fd36c2ff804b379998a90a20a875fc":{
      "scriptId":"u3"},
    "2cd90be7c2ef4264a603deb5500f413f":{
      "scriptId":"u4"},
    "281f26279b584498b404aed90bb127cf":{
      "scriptId":"u5"},
    "c967d80299ff47bca222b24e1ce69d00":{
      "scriptId":"u6"},
    "07f61ee6a41645909bbae27988e5fc26":{
      "scriptId":"u7"},
    "045d3e190fad409f8b36e0fc32d0e2f6":{
      "scriptId":"u8"},
    "4d048da6f93442d0901d1d660468ee39":{
      "scriptId":"u9"},
    "b99570c262ad4ed09a67e1c1df3eb2fd":{
      "scriptId":"u10"},
    "9ae3547df529478eab3d9c4f0a1f1b65":{
      "scriptId":"u11"},
    "10bc4aed2e134eeb98bc1b43a98c9296":{
      "scriptId":"u12"},
    "3d0228f9a8ca4760a3360ee0ad9cd70a":{
      "scriptId":"u13"},
    "3c6f1e500a344513ac40bb1584296fe8":{
      "scriptId":"u14"},
    "f509fe30dfba4b0388597b33e9aa1ef6":{
      "scriptId":"u15"},
    "9daa70d62ecb4623b1b9b2583a9b9f42":{
      "scriptId":"u16"},
    "53ffa800ada44804b927f348cd9ee9e6":{
      "scriptId":"u17"},
    "38f816cf56df4784afe39974c4d36d5e":{
      "scriptId":"u18"},
    "f7de25a752594f4eb7a3abdeb3593b07":{
      "scriptId":"u19"},
    "39400b45aae942e59706279e6e03ee0e":{
      "scriptId":"u20"},
    "6a00663d05264ca6979f42d2c6210f75":{
      "scriptId":"u21"},
    "1ef5721ee42e477dba7e5ceeef161a57":{
      "scriptId":"u22"},
    "c3d8a7e5b50d4211b1bfabb19943d406":{
      "scriptId":"u23"},
    "0c3555b1cb3e4fd58e4a3fa372a02da3":{
      "scriptId":"u24"},
    "ec3bdeec015a4b52a464e83ef29d94db":{
      "scriptId":"u25"},
    "796a5a67216b41398c3278a4052d2649":{
      "scriptId":"u26"},
    "d6f6cc03f3f74c7f8f6ee87a85241e5b":{
      "scriptId":"u27"},
    "67bee50cf61346d3a02094d93b230162":{
      "scriptId":"u28"},
    "ba3c2c3b23294eae82fb441d4f1322e2":{
      "scriptId":"u29"},
    "4c60e0bdf5f8427290b019d627eccebd":{
      "scriptId":"u30"},
    "695c83c77bcb422eb57f6553bebd75aa":{
      "scriptId":"u31"},
    "ef1c62d14b2e420f8721142915533cb5":{
      "scriptId":"u32"},
    "96b814f94a1947999fbcb0731015102f":{
      "scriptId":"u33"},
    "9fd157a8998d4b258d89fb7208ee2695":{
      "scriptId":"u34"},
    "a7769497ed0947dab1adf252b923c4f6":{
      "scriptId":"u35"},
    "2d89e974553f4e6aa729d700079663bc":{
      "scriptId":"u36"},
    "a9313045370c44ddaaa0f799f9cd018b":{
      "scriptId":"u37"},
    "0fbaa9ddd59a4ec88dc743139634ccd0":{
      "scriptId":"u38"},
    "845c3d67fa0949f1bdd1b9ca434f2897":{
      "scriptId":"u39"},
    "5486334b29ef49b4a0fe9e1845d5d989":{
      "scriptId":"u40"},
    "4dbc7a30a99d4c5db396608ef2e797ce":{
      "scriptId":"u41"},
    "7ed0212273274b80ae06669c5157d60f":{
      "scriptId":"u42"},
    "13b869a1d5174440965586e533ff03b7":{
      "scriptId":"u43"},
    "5190d10674d64f9da97636affaa4df0d":{
      "scriptId":"u44"},
    "37c92bc1afb145a88c7c2f5c89ceb7eb":{
      "scriptId":"u45"},
    "58ba3ccbac58412c9354c54ae3afe8fd":{
      "scriptId":"u46"},
    "1ae7c181922b4e168774b18ce333799f":{
      "scriptId":"u47"},
    "761509eb626b4f528c24981871cd5a9d":{
      "scriptId":"u48"},
    "9b88f9793b9343b1b8df047224cd4029":{
      "scriptId":"u49"},
    "29e104eeacb644a780a07806f2ce0ce8":{
      "scriptId":"u50"},
    "4bb4a9feabff4881ac1efda96e735cdf":{
      "scriptId":"u51"},
    "8082f7ed26af46248499654a78a90905":{
      "scriptId":"u52"},
    "10a0bb1ef63a4b11802e6686289f7c23":{
      "scriptId":"u53"},
    "dbcaf4148478433bbaccd2c988c03b67":{
      "scriptId":"u54"},
    "1668aaaab7014cd28c6253cfb7ede7c0":{
      "scriptId":"u55"},
    "718b748715704d458304065bb0fbd02d":{
      "scriptId":"u56"},
    "d8cb3442133f4311b84f049ae9d12ff3":{
      "scriptId":"u57"},
    "ccc0c029eb544effb002de5040005181":{
      "scriptId":"u58"},
    "6067b29a91bb4fedb3cf78f579fe943e":{
      "scriptId":"u59"}}});