$axure.loadCurrentPage({
  "url":"dlr_order_inprocess.html",
  "generationDate":new Date(1594096873118.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"460b8ba832ea4412886a15dc1db59e2e",
    "type":"Axure:Page",
    "name":"dlr_order_inprocess",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6141d2ccde944c0fb042b94171bc356e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1366,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a58e97b3b6b34b06bd941112440c35e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1366,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dlr_order_inprocess/u0.png"}},
{
          "id":"28108b42d5b1452ebc13b00ab407d993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "location":{
              "x":1041,
              "y":538},
            "size":{
              "width":10,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0e90d59f7c4244a4e735f17778e39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "location":{
                  "x":1041,
                  "y":538},
                "size":{
                  "width":10,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83eff65d8fa241279b1125fdfff0a273",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":37,
              "y":278},
            "size":{
              "width":78,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5867ffc1cc8743099a6463ba879b36f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":278},
                "size":{
                  "width":78,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7384a062bde455cba2bc56374ffd426",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":223},
            "size":{
              "width":1076,
              "height":267}},
          "adaptiveStyles":{
},
          "scrollbars":"horizontalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0b62fd885301492c8b0dcd9eebeebf3a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6c14c329bd7241c5bef68bab333e507a",
                  "label":"",
                  "parentDynamicPanel":"f7384a062bde455cba2bc56374ffd426",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1550,
                      "height":270}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"8fb44a10e29344018f8246a652cf9ab3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":277},
            "size":{
              "width":76,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 shopcart",
                      "target":{
                        "targetType":"page",
                        "url":"shopcart.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4761c76ebc2b40318b6ef2a11109ff62",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":305},
            "size":{
              "width":63,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d805c936b9d2495290a2b0f715a81e61",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":398},
            "size":{
              "width":70,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 dlr_all_orders",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_all_orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"043360ad73794b7fa662cbb5fbb9b441",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":584},
            "size":{
              "width":66,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 wechat_order_all",
                      "target":{
                        "targetType":"page",
                        "url":"wechat_order_all.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "6141d2ccde944c0fb042b94171bc356e":{
      "scriptId":"u0"},
    "a58e97b3b6b34b06bd941112440c35e9":{
      "scriptId":"u1"},
    "28108b42d5b1452ebc13b00ab407d993":{
      "scriptId":"u2"},
    "2c0e90d59f7c4244a4e735f17778e39f":{
      "scriptId":"u3"},
    "83eff65d8fa241279b1125fdfff0a273":{
      "scriptId":"u4"},
    "5867ffc1cc8743099a6463ba879b36f7":{
      "scriptId":"u5"},
    "f7384a062bde455cba2bc56374ffd426":{
      "scriptId":"u6"},
    "6c14c329bd7241c5bef68bab333e507a":{
      "scriptId":"u7"},
    "8fb44a10e29344018f8246a652cf9ab3":{
      "scriptId":"u8"},
    "4761c76ebc2b40318b6ef2a11109ff62":{
      "scriptId":"u9"},
    "d805c936b9d2495290a2b0f715a81e61":{
      "scriptId":"u10"},
    "043360ad73794b7fa662cbb5fbb9b441":{
      "scriptId":"u11"}}});