$axure.loadCurrentPage({
  "url":"conbine_company_internal.html",
  "generationDate":new Date(1594040143986.4),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"2609fd6cfb1d4805804e6e1c24eb7972",
    "type":"Axure:Page",
    "name":"conbine_company_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6d8b8fcf6167496c9657c869d6a61c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":2,
              "y":53},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db066c60b1854701bf47a16ef7fc6605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":2,
                  "y":53},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f3d8b56628645feb1f916d63de7a75c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":493,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65493ef5d224155807f3ff9c91dc075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":493,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/company_candidate_search_internal/u2.png"}},
{
          "id":"27307a9d64534916bded0ffc6b5f4dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":47},
            "size":{
              "width":410,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b11b305fad430384366bc6aba3d348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":47},
                "size":{
                  "width":410,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c223b5f32064aca9e9f1596c274cad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":75},
            "size":{
              "width":430,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3525df052f1143d3b8b7c040f9e4352f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":75},
                "size":{
                  "width":430,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a94e27d732c84e48a896756cbbe2c5e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":101},
            "size":{
              "width":399,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e832649a1e3c41bf8b5792ad5a27c5ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":101},
                "size":{
                  "width":399,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08a3d77fa187402c9682ddb70a1e0d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":124},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afde61d2a08543839812c582145161ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":124},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65f89ecef6e448a99872afa181ba411",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":13,
              "y":147},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"538917d33bed4ea0837f57da7146d29b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":13,
                  "y":147},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a21232ebe80142bc84918ed853252039",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":169},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26eca0de16b740eab136bdfa7d147e7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":169},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aee10fa848847da98730817367fed8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xF7F7F7},
            "location":{
              "x":170,
              "y":210},
            "size":{
              "width":28,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xF7F7F7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c82de7b6f1249169a007ddc2ea201f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xF7F7F7},
                "location":{
                  "x":170,
                  "y":210},
                "size":{
                  "width":28,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xF7F7F7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47edaa787d8b46f8b29662c99de0c7e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":104,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"794337a46af7469a9382cb9b2f59479d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":104,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u28.png"}},
{
          "id":"9d834a09303c4c0daf1a054a3276e0ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":131,
              "y":210},
            "size":{
              "width":199,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d12963f9f193452ba8d07e469f427091",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":131,
                  "y":210},
                "size":{
                  "width":199,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 companyCombination = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"companyCombination"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 create_company 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"create_company.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search/u28.png"}},
{
          "id":"dd937f8fc9774a15b73e857d88773ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xF7F7F7},
            "location":{
              "x":22,
              "y":216},
            "size":{
              "width":54,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xF7F7F7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f41a66be704e059ed852465325564d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xF7F7F7},
                "location":{
                  "x":22,
                  "y":216},
                "size":{
                  "width":54,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xF7F7F7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18e43b6f539b409ebeea416de8a6ace8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xF7F7F7},
            "location":{
              "x":159,
              "y":216},
            "size":{
              "width":134,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xF7F7F7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9d66ad515a1444f91f43ffa6bf3683a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xF7F7F7},
                "location":{
                  "x":159,
                  "y":216},
                "size":{
                  "width":134,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xF7F7F7}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 companyCombination = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"companyCombination"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 create_company 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"create_company.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cea6d6abb9c4c05ad7c70fb54bf86c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":2,
              "y":4},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09acc779c3d8447795b4016669f0f977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":2,
                  "y":4},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e9ae199fceb4b968f2dd06d3925cefd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":73,
              "y":0},
            "size":{
              "width":261,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"39d635b4996140d9abe8f82377a57c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":79,
              "y":5},
            "size":{
              "width":205,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"142c4a5c81b94265bc8f3d81c9bd6eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":79,
                  "y":5},
                "size":{
                  "width":205,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6d8b8fcf6167496c9657c869d6a61c87":{
      "scriptId":"u0"},
    "db066c60b1854701bf47a16ef7fc6605":{
      "scriptId":"u1"},
    "8f3d8b56628645feb1f916d63de7a75c":{
      "scriptId":"u2"},
    "c65493ef5d224155807f3ff9c91dc075":{
      "scriptId":"u3"},
    "27307a9d64534916bded0ffc6b5f4dda":{
      "scriptId":"u4"},
    "28b11b305fad430384366bc6aba3d348":{
      "scriptId":"u5"},
    "7c223b5f32064aca9e9f1596c274cad3":{
      "scriptId":"u6"},
    "3525df052f1143d3b8b7c040f9e4352f":{
      "scriptId":"u7"},
    "a94e27d732c84e48a896756cbbe2c5e2":{
      "scriptId":"u8"},
    "e832649a1e3c41bf8b5792ad5a27c5ad":{
      "scriptId":"u9"},
    "08a3d77fa187402c9682ddb70a1e0d9c":{
      "scriptId":"u10"},
    "afde61d2a08543839812c582145161ea":{
      "scriptId":"u11"},
    "d65f89ecef6e448a99872afa181ba411":{
      "scriptId":"u12"},
    "538917d33bed4ea0837f57da7146d29b":{
      "scriptId":"u13"},
    "a21232ebe80142bc84918ed853252039":{
      "scriptId":"u14"},
    "26eca0de16b740eab136bdfa7d147e7f":{
      "scriptId":"u15"},
    "9aee10fa848847da98730817367fed8f":{
      "scriptId":"u16"},
    "1c82de7b6f1249169a007ddc2ea201f2":{
      "scriptId":"u17"},
    "47edaa787d8b46f8b29662c99de0c7e8":{
      "scriptId":"u18"},
    "794337a46af7469a9382cb9b2f59479d":{
      "scriptId":"u19"},
    "9d834a09303c4c0daf1a054a3276e0ea":{
      "scriptId":"u20"},
    "d12963f9f193452ba8d07e469f427091":{
      "scriptId":"u21"},
    "dd937f8fc9774a15b73e857d88773ed9":{
      "scriptId":"u22"},
    "38f41a66be704e059ed852465325564d":{
      "scriptId":"u23"},
    "18e43b6f539b409ebeea416de8a6ace8":{
      "scriptId":"u24"},
    "a9d66ad515a1444f91f43ffa6bf3683a":{
      "scriptId":"u25"},
    "6cea6d6abb9c4c05ad7c70fb54bf86c1":{
      "scriptId":"u26"},
    "09acc779c3d8447795b4016669f0f977":{
      "scriptId":"u27"},
    "4e9ae199fceb4b968f2dd06d3925cefd":{
      "scriptId":"u28"},
    "39d635b4996140d9abe8f82377a57c26":{
      "scriptId":"u29"},
    "142c4a5c81b94265bc8f3d81c9bd6eec":{
      "scriptId":"u30"}}});