$axure.loadCurrentPage({
  "url":"fundamental_data.html",
  "generationDate":new Date(1594096932819.36),
  "isCanvasEnabled":false,
  "variables":["show_data_updated_tip"],
  "page":{
    "packageId":"89146c5dd91b4f7a8de7100e9b3e9adb",
    "type":"Axure:Page",
    "name":"fundamental_data",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"818351a12b054699b38d05191c172ad7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1348,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff87718eb459410aa08e4638b2adc38d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1348,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u0.png"}},
{
          "id":"182b81896f054ef9a5a87ede849230af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":163,
              "height":819}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44d1d916c8a54f0a8b10ea89fb7dfbd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":163,
                  "height":819}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"062e689ea8f44dbe9fff537a1f7e9b35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":163,
              "y":60},
            "size":{
              "width":18,
              "height":819}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f41ad323a4024aedaeed19e8becacd09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":163,
                  "y":60},
                "size":{
                  "width":18,
                  "height":819}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u4.png"}},
{
          "id":"57fb24ff16cf42b6ae2cfd969c3b3ba5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":179,
              "y":60},
            "size":{
              "width":1168,
              "height":819}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05a1eb73c4824d22b65d105fbbb38d33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":179,
                  "y":60},
                "size":{
                  "width":1168,
                  "height":819}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u6.png"}},
{
          "id":"747b3944507e464380a4a1b757c1b9c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":24,
              "y":203},
            "size":{
              "width":126,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1a2881cebf4dd39e8fd84d3d9c4969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":24,
                  "y":203},
                "size":{
                  "width":126,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u8.png"}},
{
          "id":"d09cee4dcaa24297ab1befd0b4be5f8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1DAFED,
              "opacity":1},
            "location":{
              "x":37,
              "y":210},
            "size":{
              "width":78,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"334521965d1f495aae57ba16c481a384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1DAFED,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":210},
                "size":{
                  "width":78,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86920dc75b584420b865797134cb37ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":37,
              "y":177},
            "size":{
              "width":108,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f470be2b4b4b46c7b6e83296bcdf27cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":177},
                "size":{
                  "width":108,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cbc7e7f649c4571bb40bc3e6cdfb402",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":218,
              "y":109},
            "size":{
              "width":1086,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"669b01ad172546038a1d271ab95377b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":218,
                  "y":109},
                "size":{
                  "width":1086,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fundamental_data/u14.png"}},
{
          "id":"8e4c1102db484d16990885a97c2b3e8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1054,
              "y":169},
            "size":{
              "width":117,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48a609da44a4de79950b877e18fba87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1054,
                  "y":169},
                "size":{
                  "width":117,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fundamental_data/u16.png"}},
{
          "id":"71a712f5350f40a29cd8d7e982fde16b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":717,
              "y":788},
            "size":{
              "width":583,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2797a9b36039400bb06b327cb5550ef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":717,
                  "y":788},
                "size":{
                  "width":583,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fundamental_data/u18.png"}},
{
          "id":"f8dedf2bd45f461d8d7e3a386655a99c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":219},
            "size":{
              "width":1078,
              "height":559}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1<br> (If 值于 show_data_updated_tip 等于 &quot;1&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"show_data_updated_tip"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1",
                      "stos":[]}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 data_updated_tip",
                      "objectsToFades":[{
                          "objectPath":["104d41193cf84a8b94be4bceda958504"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待2500毫秒",
                      "waitTime":2500},
{
                      "action":"fadeWidget",
                      "description":"隐藏 data_updated_tip",
                      "objectsToFades":[{
                          "objectPath":["104d41193cf84a8b94be4bceda958504"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setFunction",
                      "description":"设置 值于 show_data_updated_tip = &quot;0&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"show_data_updated_tip"},
{
                                "exprType":"stringLiteral",
                                "value":"0",
                                "stos":[]}]}]}}]}]}},
          "scrollbars":"horizontalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1865569ac2d846198f65c7efba85cad0",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"63664bd1e7574002aaeb726997705231",
                  "label":"",
                  "parentDynamicPanel":"f8dedf2bd45f461d8d7e3a386655a99c",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1750,
                      "height":550}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"903651a2b267471ca79383d10d43ee0f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":173},
            "size":{
              "width":123,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e337021c602b4cbd9bfa5ce989cb8902",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1053,
              "y":169},
            "size":{
              "width":118,
              "height":31}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 conflict_handle",
                      "target":{
                        "targetType":"page",
                        "url":"conflict_handle.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"104d41193cf84a8b94be4bceda958504",
          "label":"data_updated_tip",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":584,
              "y":13},
            "size":{
              "width":180,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582836bb983c411d9f3a8a4b94d500fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":584,
                  "y":13},
                "size":{
                  "width":180,
                  "height":35},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/fundamental_data/data_updated_tip_u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "818351a12b054699b38d05191c172ad7":{
      "scriptId":"u0"},
    "ff87718eb459410aa08e4638b2adc38d":{
      "scriptId":"u1"},
    "182b81896f054ef9a5a87ede849230af":{
      "scriptId":"u2"},
    "44d1d916c8a54f0a8b10ea89fb7dfbd5":{
      "scriptId":"u3"},
    "062e689ea8f44dbe9fff537a1f7e9b35":{
      "scriptId":"u4"},
    "f41ad323a4024aedaeed19e8becacd09":{
      "scriptId":"u5"},
    "57fb24ff16cf42b6ae2cfd969c3b3ba5":{
      "scriptId":"u6"},
    "05a1eb73c4824d22b65d105fbbb38d33":{
      "scriptId":"u7"},
    "747b3944507e464380a4a1b757c1b9c1":{
      "scriptId":"u8"},
    "5f1a2881cebf4dd39e8fd84d3d9c4969":{
      "scriptId":"u9"},
    "d09cee4dcaa24297ab1befd0b4be5f8c":{
      "scriptId":"u10"},
    "334521965d1f495aae57ba16c481a384":{
      "scriptId":"u11"},
    "86920dc75b584420b865797134cb37ca":{
      "scriptId":"u12"},
    "f470be2b4b4b46c7b6e83296bcdf27cc":{
      "scriptId":"u13"},
    "1cbc7e7f649c4571bb40bc3e6cdfb402":{
      "scriptId":"u14"},
    "669b01ad172546038a1d271ab95377b9":{
      "scriptId":"u15"},
    "8e4c1102db484d16990885a97c2b3e8c":{
      "scriptId":"u16"},
    "a48a609da44a4de79950b877e18fba87":{
      "scriptId":"u17"},
    "71a712f5350f40a29cd8d7e982fde16b":{
      "scriptId":"u18"},
    "2797a9b36039400bb06b327cb5550ef8":{
      "scriptId":"u19"},
    "f8dedf2bd45f461d8d7e3a386655a99c":{
      "scriptId":"u20"},
    "63664bd1e7574002aaeb726997705231":{
      "scriptId":"u21"},
    "903651a2b267471ca79383d10d43ee0f":{
      "scriptId":"u22"},
    "e337021c602b4cbd9bfa5ce989cb8902":{
      "scriptId":"u23"},
    "104d41193cf84a8b94be4bceda958504":{
      "scriptId":"u24"},
    "582836bb983c411d9f3a8a4b94d500fc":{
      "scriptId":"u25"}}});