$axure.loadCurrentPage({
  "url":"upload_picture_inframe.html",
  "generationDate":new Date(1594096788810.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"87b70bccc1ee4adeb547c01175dc5037",
    "type":"Axure:Page",
    "name":"upload_picture_inframe",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF070616},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f598e458727442539b5772a937527c8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699FF,
              "opacity":1},
            "location":{
              "x":21,
              "y":49},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df3f985b934492a9be5ba79c475bd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699FF,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":49},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcda4a393dd24c69aee80cc799807a7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":231,
              "y":44},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e054af1e914d03ae056582366613fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":231,
                  "y":44},
                "size":{
                  "width":80,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 camera_picture_option",
                      "objectsToFades":[{
                          "objectPath":["a085642aff3c4919b9ce516005ece34a"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u2.png"}},
{
          "id":"53927e25f461476982705491b5ed6eef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":320,
              "y":44},
            "size":{
              "width":79,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d2b3cf500341119bc4c9b2b2e8cd7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":320,
                  "y":44},
                "size":{
                  "width":79,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/upload_picture_inframe/u4.png"}},
{
          "id":"fbd93d89885e45b6a9148b743bc4c90e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":21,
              "y":85},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"127238fcd68844eea8eb555fc813fbb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":21,
                  "y":85},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a26484188cf046a5a61fa8f455a4fa8c",
          "label":"delete_picture_tip",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":290,
              "y":26},
            "size":{
              "width":113,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172aac6eb0b74efa8895401ca0c5fcdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":26},
                "size":{
                  "width":113,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"690c9dc401684e1f9e9f0690765b0abb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":22,
              "y":105},
            "size":{
              "width":112,
              "height":112}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6a0d9679aa04c47859fd6cd56b7fd9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":22,
                  "y":105},
                "size":{
                  "width":112,
                  "height":112}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u10.jpg"}},
{
          "id":"875060eaf5cc44d48282fc2579bad9b9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":86},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eff5aa5644344de8871f022c001a5be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":86},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a2d7b7f6f48c442489ae18654ddfa01c",
          "label":"add_picture_tip",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":90,
              "y":4},
            "size":{
              "width":191,
              "height":34},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7305b4e68f14cf6adb23ae35f51b1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":4},
                "size":{
                  "width":191,
                  "height":34},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d01d976b95941efa585c80f7b0cc874",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":153,
              "y":106},
            "size":{
              "width":116,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c168e10bffb74f6ba265a4dd7f3395dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":153,
                  "y":106},
                "size":{
                  "width":116,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u16.jpg"}},
{
          "id":"3995b5a02d8446cf9b502ccdb3876467",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699FF,
              "opacity":1},
            "location":{
              "x":18,
              "y":248},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc67c6cdecb4ed8be5ad3c742b8424e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699FF,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":248},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"752fc57552494f499a09859b1efad421",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":228,
              "y":243},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab5eac6fe4c4dd48779bea180a19ee6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":228,
                  "y":243},
                "size":{
                  "width":80,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 camera_picture_option",
                      "objectsToFades":[{
                          "objectPath":["a085642aff3c4919b9ce516005ece34a"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u2.png"}},
{
          "id":"69afb352de5642cf9b4bd827377b9f17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":317,
              "y":243},
            "size":{
              "width":79,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6d07c1cd694c988c5178004bb9dccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":317,
                  "y":243},
                "size":{
                  "width":79,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/upload_picture_inframe/u4.png"}},
{
          "id":"9989599d8f1647afa898c6dd5e37fc7d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":268},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca3da3dde713479f86dda47ca3a5f48b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":268},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4aa3e12397774c0bb3caf119cf1cee71",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":149,
              "y":269},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbabecbc23f46cb872c5f8d877e1765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":149,
                  "y":269},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6d60a65084684a81a2c8d9a72b557643",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":21,
              "y":294},
            "size":{
              "width":113,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c29980000948658ae4f7e026b28d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":21,
                  "y":294},
                "size":{
                  "width":113,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u28.jpg"}},
{
          "id":"2e11560817dd43ec974a647fbc4fe62d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":149,
              "y":295},
            "size":{
              "width":127,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2bd136c14145ebb4ce4999d927e78d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":149,
                  "y":295},
                "size":{
                  "width":127,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u30.jpg"}},
{
          "id":"85d3aa8f476f40b0a2eb38be34252b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699FF,
              "opacity":1},
            "location":{
              "x":17,
              "y":431},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351ce2385e96401983d3ecf9e7d3d663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699FF,
                  "opacity":1},
                "location":{
                  "x":17,
                  "y":431},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b1848f9c2ce4d8c97ecc8a71f5b2fa1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":227,
              "y":426},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00ca86c879443ac981d8d18c8316077",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":227,
                  "y":426},
                "size":{
                  "width":80,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 camera_picture_option",
                      "objectsToFades":[{
                          "objectPath":["a085642aff3c4919b9ce516005ece34a"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u2.png"}},
{
          "id":"83a51c00ee564c07b47ee28e7dd4473d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":316,
              "y":426},
            "size":{
              "width":79,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5508a9ef57748cabe78351ac5b9b143",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":316,
                  "y":426},
                "size":{
                  "width":79,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/upload_picture_inframe/u4.png"}},
{
          "id":"c5dfb5a42fd44af7b351a6975c8adc3e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":19,
              "y":451},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"822320d330774886bad47bf9002caa84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":19,
                  "y":451},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4f5964d30e1544fb8f71253fdc291d18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":477},
            "size":{
              "width":111,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17d52f20b7c541f5a1e31d516ef699e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":477},
                "size":{
                  "width":111,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u40.jpg"}},
{
          "id":"7a6fa5bd8d444f258df55d23ed8622ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6699FF,
              "opacity":1},
            "location":{
              "x":16,
              "y":613},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e9bf39a731414ab66ae7362df8f739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6699FF,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":613},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaa370359c5b407d9253db60ecfabf93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":315,
              "y":608},
            "size":{
              "width":79,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d1b12ee281247c7b4acd7fa09c1cca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":315,
                  "y":608},
                "size":{
                  "width":79,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 delete_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a26484188cf046a5a61fa8f455a4fa8c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/upload_picture_inframe/u4.png"}},
{
          "id":"e725d6a320ef4251a60c200bea14d591",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":18,
              "y":633},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c06b81f810419c90b193e6ce463376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":18,
                  "y":633},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"cc45b63e95b64ca898c52d77edb75063",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":19,
              "y":659},
            "size":{
              "width":113,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0a4a2bf31204e628ecd9f256b92f8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":19,
                  "y":659},
                "size":{
                  "width":113,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u48.jpg"}},
{
          "id":"ca6c9d2b74e44aacb80f6dfeb1f91799",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":226,
              "y":607},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad72ad20cd5d42e489d6cdb69397e002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":226,
                  "y":607},
                "size":{
                  "width":80,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 camera_picture_option",
                      "objectsToFades":[{
                          "objectPath":["a085642aff3c4919b9ce516005ece34a"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 add_picture_tip",
                      "objectsToFades":[{
                          "objectPath":["a2d7b7f6f48c442489ae18654ddfa01c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u2.png"}},
{
          "id":"a085642aff3c4919b9ce516005ece34a",
          "label":"camera_picture_option",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":457},
            "size":{
              "width":414,
              "height":115},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ea3d375743431aaff61231cc450c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":457},
                "size":{
                  "width":414,
                  "height":115},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 camera_picture_option",
                      "objectsToFades":[{
                          "objectPath":["a085642aff3c4919b9ce516005ece34a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 camera_picture_option_tip",
                      "objectsToFades":[{
                          "objectPath":["7cb201d01f324057913b2293e4159e31"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 camera_picture_option_tip",
                      "objectsToFades":[{
                          "objectPath":["7cb201d01f324057913b2293e4159e31"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/camera_picture_option_u52.jpg"}},
{
          "id":"7cb201d01f324057913b2293e4159e31",
          "label":"camera_picture_option_tip",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":2,
              "y":443},
            "size":{
              "width":412,
              "height":11},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69cf160b54ab46599c10f3c852d3ea63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":2,
                  "y":443},
                "size":{
                  "width":412,
                  "height":11},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f598e458727442539b5772a937527c8a":{
      "scriptId":"u0"},
    "8df3f985b934492a9be5ba79c475bd4f":{
      "scriptId":"u1"},
    "bcda4a393dd24c69aee80cc799807a7c":{
      "scriptId":"u2"},
    "83e054af1e914d03ae056582366613fc":{
      "scriptId":"u3"},
    "53927e25f461476982705491b5ed6eef":{
      "scriptId":"u4"},
    "11d2b3cf500341119bc4c9b2b2e8cd7b":{
      "scriptId":"u5"},
    "fbd93d89885e45b6a9148b743bc4c90e":{
      "scriptId":"u6"},
    "127238fcd68844eea8eb555fc813fbb2":{
      "scriptId":"u7"},
    "a26484188cf046a5a61fa8f455a4fa8c":{
      "scriptId":"u8"},
    "172aac6eb0b74efa8895401ca0c5fcdb":{
      "scriptId":"u9"},
    "690c9dc401684e1f9e9f0690765b0abb":{
      "scriptId":"u10"},
    "f6a0d9679aa04c47859fd6cd56b7fd9c":{
      "scriptId":"u11"},
    "875060eaf5cc44d48282fc2579bad9b9":{
      "scriptId":"u12"},
    "5eff5aa5644344de8871f022c001a5be":{
      "scriptId":"u13"},
    "a2d7b7f6f48c442489ae18654ddfa01c":{
      "scriptId":"u14"},
    "d7305b4e68f14cf6adb23ae35f51b1e1":{
      "scriptId":"u15"},
    "7d01d976b95941efa585c80f7b0cc874":{
      "scriptId":"u16"},
    "c168e10bffb74f6ba265a4dd7f3395dc":{
      "scriptId":"u17"},
    "3995b5a02d8446cf9b502ccdb3876467":{
      "scriptId":"u18"},
    "ebc67c6cdecb4ed8be5ad3c742b8424e":{
      "scriptId":"u19"},
    "752fc57552494f499a09859b1efad421":{
      "scriptId":"u20"},
    "eab5eac6fe4c4dd48779bea180a19ee6":{
      "scriptId":"u21"},
    "69afb352de5642cf9b4bd827377b9f17":{
      "scriptId":"u22"},
    "ee6d07c1cd694c988c5178004bb9dccf":{
      "scriptId":"u23"},
    "9989599d8f1647afa898c6dd5e37fc7d":{
      "scriptId":"u24"},
    "ca3da3dde713479f86dda47ca3a5f48b":{
      "scriptId":"u25"},
    "4aa3e12397774c0bb3caf119cf1cee71":{
      "scriptId":"u26"},
    "edbabecbc23f46cb872c5f8d877e1765":{
      "scriptId":"u27"},
    "6d60a65084684a81a2c8d9a72b557643":{
      "scriptId":"u28"},
    "94c29980000948658ae4f7e026b28d24":{
      "scriptId":"u29"},
    "2e11560817dd43ec974a647fbc4fe62d":{
      "scriptId":"u30"},
    "1d2bd136c14145ebb4ce4999d927e78d":{
      "scriptId":"u31"},
    "85d3aa8f476f40b0a2eb38be34252b15":{
      "scriptId":"u32"},
    "351ce2385e96401983d3ecf9e7d3d663":{
      "scriptId":"u33"},
    "2b1848f9c2ce4d8c97ecc8a71f5b2fa1":{
      "scriptId":"u34"},
    "e00ca86c879443ac981d8d18c8316077":{
      "scriptId":"u35"},
    "83a51c00ee564c07b47ee28e7dd4473d":{
      "scriptId":"u36"},
    "c5508a9ef57748cabe78351ac5b9b143":{
      "scriptId":"u37"},
    "c5dfb5a42fd44af7b351a6975c8adc3e":{
      "scriptId":"u38"},
    "822320d330774886bad47bf9002caa84":{
      "scriptId":"u39"},
    "4f5964d30e1544fb8f71253fdc291d18":{
      "scriptId":"u40"},
    "17d52f20b7c541f5a1e31d516ef699e5":{
      "scriptId":"u41"},
    "7a6fa5bd8d444f258df55d23ed8622ff":{
      "scriptId":"u42"},
    "14e9bf39a731414ab66ae7362df8f739":{
      "scriptId":"u43"},
    "eaa370359c5b407d9253db60ecfabf93":{
      "scriptId":"u44"},
    "0d1b12ee281247c7b4acd7fa09c1cca7":{
      "scriptId":"u45"},
    "e725d6a320ef4251a60c200bea14d591":{
      "scriptId":"u46"},
    "76c06b81f810419c90b193e6ce463376":{
      "scriptId":"u47"},
    "cc45b63e95b64ca898c52d77edb75063":{
      "scriptId":"u48"},
    "e0a4a2bf31204e628ecd9f256b92f8ce":{
      "scriptId":"u49"},
    "ca6c9d2b74e44aacb80f6dfeb1f91799":{
      "scriptId":"u50"},
    "ad72ad20cd5d42e489d6cdb69397e002":{
      "scriptId":"u51"},
    "a085642aff3c4919b9ce516005ece34a":{
      "scriptId":"u52"},
    "c6ea3d375743431aaff61231cc450c9b":{
      "scriptId":"u53"},
    "7cb201d01f324057913b2293e4159e31":{
      "scriptId":"u54"},
    "69cf160b54ab46599c10f3c852d3ea63":{
      "scriptId":"u55"}}});