$axure.loadCurrentPage({
  "url":"selectdealer.html",
  "generationDate":new Date(1594096576300.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"41436547344344f39c6019d8233cc9eb",
    "type":"Axure:Page",
    "name":"selectdealer",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"43f17a497da04041bc263681d25ad1c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":412,
              "height":829}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82c47d4e5d5e4628a11c7b451877132f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":412,
                  "height":829}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/selectdealer/u0.jpg"}},
{
          "id":"7303e7ac336c4cc8bac99633e000a80f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":72},
            "size":{
              "width":33,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 offerhome",
                      "target":{
                        "targetType":"page",
                        "url":"offerhome.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"15a49c988d054d27a25191f2c765af37",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":105},
            "size":{
              "width":405,
              "height":700}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"bcf637bea21d4a18a5fc1d8a9c2c1e66",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ea20ddb4e50448ad86d8b519410e1782",
                  "label":"",
                  "parentDynamicPanel":"15a49c988d054d27a25191f2c765af37",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":364,
                      "height":775}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"d127f03cef79458599ef8da3d480e283",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":387,
              "y":105},
            "size":{
              "width":47,
              "height":703}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bfb2ec381044c82b7b2e633e8d489bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":387,
                  "y":105},
                "size":{
                  "width":47,
                  "height":703}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/offerhome/u4.jpg"}},
{
          "id":"88420b71f0be448bae5175293a6aa62d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":72},
            "size":{
              "width":30,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "43f17a497da04041bc263681d25ad1c8":{
      "scriptId":"u0"},
    "82c47d4e5d5e4628a11c7b451877132f":{
      "scriptId":"u1"},
    "7303e7ac336c4cc8bac99633e000a80f":{
      "scriptId":"u2"},
    "15a49c988d054d27a25191f2c765af37":{
      "scriptId":"u3"},
    "ea20ddb4e50448ad86d8b519410e1782":{
      "scriptId":"u4"},
    "d127f03cef79458599ef8da3d480e283":{
      "scriptId":"u5"},
    "3bfb2ec381044c82b7b2e633e8d489bf":{
      "scriptId":"u6"},
    "88420b71f0be448bae5175293a6aa62d":{
      "scriptId":"u7"}}});