$axure.loadCurrentPage({
  "url":"elementslist_inline.html",
  "generationDate":new Date(1594096576686.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b12adf4193f64bcaa6a9ff4224bfb8b1",
    "type":"Axure:Page",
    "name":"elementslist_inline",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e24d33933d0d43c6bd26243155450bfb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":364,
              "height":1051}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ded7b38ebd84a6b8c40bd57be241a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":364,
                  "height":1051}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elementslist_inline/u0.jpg"}},
{
          "id":"8fe7c2d52cf34eef817e62bb01591c47",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":321,
              "y":21},
            "size":{
              "width":39,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[]},
{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 orderlist 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"orderlist.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true},
{
          "id":"a0ce01271f4c439290b6f5fd8843132e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":16,
              "y":84},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77d68da2ccfd4f4a9a8ede9707e86a8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":84},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a44937ed99cd4d99a275c2f79a76a9aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":16,
              "y":597},
            "size":{
              "width":62,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee5aacbd8354baa8d895ec000a48e92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":597},
                "size":{
                  "width":62,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"118d7fb337e845aca3105205ecc1b725",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":166,
              "y":1004},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"584949f673f94aa68fd2df4bb370ec62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":166,
                  "y":1004},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d734e3b9b20e4f90b390e87d181c74ed",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":1004},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 generateorder 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"generateorder.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "e24d33933d0d43c6bd26243155450bfb":{
      "scriptId":"u0"},
    "4ded7b38ebd84a6b8c40bd57be241a65":{
      "scriptId":"u1"},
    "8fe7c2d52cf34eef817e62bb01591c47":{
      "scriptId":"u2"},
    "a0ce01271f4c439290b6f5fd8843132e":{
      "scriptId":"u3"},
    "77d68da2ccfd4f4a9a8ede9707e86a8d":{
      "scriptId":"u4"},
    "a44937ed99cd4d99a275c2f79a76a9aa":{
      "scriptId":"u5"},
    "9ee5aacbd8354baa8d895ec000a48e92":{
      "scriptId":"u6"},
    "118d7fb337e845aca3105205ecc1b725":{
      "scriptId":"u7"},
    "584949f673f94aa68fd2df4bb370ec62":{
      "scriptId":"u8"},
    "d734e3b9b20e4f90b390e87d181c74ed":{
      "scriptId":"u9"}}});