$axure.loadCurrentPage({
  "url":"order_details_inframe.html",
  "generationDate":new Date(1594096788930.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a944c4207d604f7f82f7d9eb8c6d7263",
    "type":"Axure:Page",
    "name":"order_details_inframe",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF070616},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f8b84394273f48b0958d92b28d6ca384",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":414,
              "height":487}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90018eda92cf43f6abe318c78339676a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":414,
                  "height":487}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/order_details_inframe/u0.png"}},
{
          "id":"b3eacd6f58ff4141b026b80233318b60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF0B090C},
            "location":{
              "x":0,
              "y":482},
            "size":{
              "width":414,
              "height":498},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ddc28545538479790d2516092184699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0B090C},
                "location":{
                  "x":0,
                  "y":482},
                "size":{
                  "width":414,
                  "height":498},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/order_details_inframe/u2.png"}},
{
          "id":"599c0c604eed45ee9e3fb87cd1cb2c76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":15,
              "y":496},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b557299d834d55a6c7e2a2c70cd8b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":496},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d06758711ff341ac98f1720ea02d5d96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":518},
            "size":{
              "width":111,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb9848e67b694963848a771262a6cb38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":518},
                "size":{
                  "width":111,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u40.jpg"}},
{
          "id":"3808982e7f9a4c5d9a3c6a5a7fd5e40b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":140,
              "y":518},
            "size":{
              "width":112,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff22a3a02db4a6789fcc08965b48a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":140,
                  "y":518},
                "size":{
                  "width":112,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u10.jpg"}},
{
          "id":"b85d0638b8c645b2ad384431bb36c84b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":15,
              "y":641},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a76abd2f8f054190b9ad132a955ff106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":641},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2db8dfe84deb43a3b2895ff79024b454",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":670},
            "size":{
              "width":116,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27bf573b66a54e03971feca78fd7f49a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":670},
                "size":{
                  "width":116,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u16.jpg"}},
{
          "id":"e42697f4cda14f41859a56783fee2836",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":15,
              "y":804},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192367c4de994f9498da7590e33312aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":804},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7306e122642048f9b9b737c138e50375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":837},
            "size":{
              "width":127,
              "height":123}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6900c2cccf94576b0890c8126d2fd9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":837},
                "size":{
                  "width":127,
                  "height":123}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u30.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "f8b84394273f48b0958d92b28d6ca384":{
      "scriptId":"u0"},
    "90018eda92cf43f6abe318c78339676a":{
      "scriptId":"u1"},
    "b3eacd6f58ff4141b026b80233318b60":{
      "scriptId":"u2"},
    "9ddc28545538479790d2516092184699":{
      "scriptId":"u3"},
    "599c0c604eed45ee9e3fb87cd1cb2c76":{
      "scriptId":"u4"},
    "47b557299d834d55a6c7e2a2c70cd8b0":{
      "scriptId":"u5"},
    "d06758711ff341ac98f1720ea02d5d96":{
      "scriptId":"u6"},
    "bb9848e67b694963848a771262a6cb38":{
      "scriptId":"u7"},
    "3808982e7f9a4c5d9a3c6a5a7fd5e40b":{
      "scriptId":"u8"},
    "2ff22a3a02db4a6789fcc08965b48a1e":{
      "scriptId":"u9"},
    "b85d0638b8c645b2ad384431bb36c84b":{
      "scriptId":"u10"},
    "a76abd2f8f054190b9ad132a955ff106":{
      "scriptId":"u11"},
    "2db8dfe84deb43a3b2895ff79024b454":{
      "scriptId":"u12"},
    "27bf573b66a54e03971feca78fd7f49a":{
      "scriptId":"u13"},
    "e42697f4cda14f41859a56783fee2836":{
      "scriptId":"u14"},
    "192367c4de994f9498da7590e33312aa":{
      "scriptId":"u15"},
    "7306e122642048f9b9b737c138e50375":{
      "scriptId":"u16"},
    "c6900c2cccf94576b0890c8126d2fd9e":{
      "scriptId":"u17"}}});