$axure.loadCurrentPage({
  "url":"quotation_list.html",
  "generationDate":new Date(1594037920363.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"813d1565c58c410ea5c11538a635f9eb",
    "type":"Axure:Page",
    "name":"quotation_list",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41deb2e1e85d4326a822ffce2c52f95a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1360,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0669f7f5cf54bf588fac2ff1908332a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1360,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u0.png"}},
{
          "id":"a118415fb33e481d98f68f5b12a1cdd0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":132},
            "size":{
              "width":1360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/e3_view/u2_line.png"}},
{
          "id":"ba7232a0eb794a0fbd2bf91cfeacf354",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":171},
            "size":{
              "width":1360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/e3_view/u2_line.png"}},
{
          "id":"432d3b3f2df94d7da7eb2d8e21d59975",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F0F0},
            "location":{
              "x":0,
              "y":138},
            "size":{
              "width":1360,
              "height":38},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b24adadd4674cd8818a9bbac7da68a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F0F0},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":1360,
                  "height":38},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u4.png"}},
{
          "id":"95a7b0c1a8714936854825d4f7d33492",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF274044,
              "opacity":1},
            "location":{
              "x":26,
              "y":146},
            "size":{
              "width":220,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80df924a12484a98b819c9ad1ea27732",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF274044,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":146},
                "size":{
                  "width":220,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9206c06269904809b9731346ad6d8fab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":26,
              "y":559},
            "size":{
              "width":598,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be12579524446dea432755739a3eac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":26,
                  "y":559},
                "size":{
                  "width":598,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/e3_view/u54.png"}},
{
          "id":"6d4c30ff7ea94e61a76b22390a3df8e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":26,
              "y":203},
            "size":{
              "width":205,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a257d79a5e49558f7147845b9ec2cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":203},
                "size":{
                  "width":205,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/phase_time_report/u8.png"}},
{
          "id":"5c3ec1e0d09d4232bb6066b8daf51eb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":39,
              "y":214},
            "size":{
              "width":43,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3884970f7024bf58a0cc3e6e3cc360f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":39,
                  "y":214},
                "size":{
                  "width":43,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8afab0dd5de74f17b49e6b6017384e45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":247,
              "y":203},
            "size":{
              "width":205,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f91e7aa85944c4e926449fcc68cd42f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":203},
                "size":{
                  "width":205,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/phase_time_report/u40.png"}},
{
          "id":"5735718c715c49408444a9b207f281bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":468,
              "y":203},
            "size":{
              "width":205,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69306aa1844347b081e192cc170dc5a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":468,
                  "y":203},
                "size":{
                  "width":205,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/phase_time_report/u40.png"}},
{
          "id":"a9e4bd32185f4d1389c4da6ed9b54e1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":481,
              "y":214},
            "size":{
              "width":68,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9143d9bb53ab4d728b4e12dec01a1cf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":481,
                  "y":214},
                "size":{
                  "width":68,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77b18015f10e4f2e885cde9eec09bc7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":689,
              "y":203},
            "size":{
              "width":205,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"698a5a73221544dfa493fb7f5113bf8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":689,
                  "y":203},
                "size":{
                  "width":205,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/phase_time_report/u40.png"}},
{
          "id":"7b06b0397dd84a31bdbaaf0b0f26392b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":702,
              "y":214},
            "size":{
              "width":53,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6164af066e9143a8b708145a49cf1922",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":702,
                  "y":214},
                "size":{
                  "width":53,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"297f582c7c5a41fb9bf3da3d700f039e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":913,
              "y":203},
            "size":{
              "width":205,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5045385ea84943b02f557595a0ec2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":913,
                  "y":203},
                "size":{
                  "width":205,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/phase_time_report/u40.png"}},
{
          "id":"0a10af40b18c473d89e6c2284541a9d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFAFAEE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF274044},
            "location":{
              "x":164,
              "y":260},
            "size":{
              "width":110,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c316c4493235454489e222ed0623d6b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFAFAEE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF274044},
                "location":{
                  "x":164,
                  "y":260},
                "size":{
                  "width":110,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_new_server_demand/u14.png"}},
{
          "id":"ecbd32c41d6842029b33898b9b1a4910",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFAFAEE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF274044},
            "location":{
              "x":26,
              "y":260},
            "size":{
              "width":110,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51487ff2a74b48e886d4c29b14fc62d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFAFAEE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF274044},
                "location":{
                  "x":26,
                  "y":260},
                "size":{
                  "width":110,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/employee_new_server_demand/u14.png"}},
{
          "id":"c5f9ca1cd9354c83b1773467044eac8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFAFAEE,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF274044},
            "location":{
              "x":302,
              "y":260},
            "size":{
              "width":120,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a419116af547f587cd0c8f293c9263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFAFAEE,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF274044},
                "location":{
                  "x":302,
                  "y":260},
                "size":{
                  "width":120,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/phase_time_report/u100.png"}},
{
          "id":"d05c07b6886d40f7bbc8c2c8f20e9b54",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":349},
            "size":{
              "width":1242,
              "height":145}},
          "adaptiveStyles":{
},
          "scrollbars":"horizontalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2beb13d06c9647e5a3c7d47e71ff7c6f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c53d465cfb6a489b9b8e98ac95bb7bf1",
                  "label":"",
                  "parentDynamicPanel":"d05c07b6886d40f7bbc8c2c8f20e9b54",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":3050,
                      "height":125}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"e6f8fd7680ce4b5c99f2db19aa8609a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":28,
              "y":500},
            "size":{
              "width":43,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64813afe091b40fe96de354aa2302e65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":28,
                  "y":500},
                "size":{
                  "width":43,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/quotation_list/u34.png"}},
{
          "id":"78bc13fb135043de87e6d79eefdac2d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":47,
              "y":312},
            "size":{
              "width":99,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60b778368a9949ea913121a7ee13271f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":47,
                  "y":312},
                "size":{
                  "width":99,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "41deb2e1e85d4326a822ffce2c52f95a":{
      "scriptId":"u0"},
    "b0669f7f5cf54bf588fac2ff1908332a":{
      "scriptId":"u1"},
    "a118415fb33e481d98f68f5b12a1cdd0":{
      "scriptId":"u2"},
    "ba7232a0eb794a0fbd2bf91cfeacf354":{
      "scriptId":"u3"},
    "432d3b3f2df94d7da7eb2d8e21d59975":{
      "scriptId":"u4"},
    "7b24adadd4674cd8818a9bbac7da68a8":{
      "scriptId":"u5"},
    "95a7b0c1a8714936854825d4f7d33492":{
      "scriptId":"u6"},
    "80df924a12484a98b819c9ad1ea27732":{
      "scriptId":"u7"},
    "9206c06269904809b9731346ad6d8fab":{
      "scriptId":"u8"},
    "3be12579524446dea432755739a3eac8":{
      "scriptId":"u9"},
    "6d4c30ff7ea94e61a76b22390a3df8e8":{
      "scriptId":"u10"},
    "10a257d79a5e49558f7147845b9ec2cf":{
      "scriptId":"u11"},
    "5c3ec1e0d09d4232bb6066b8daf51eb5":{
      "scriptId":"u12"},
    "f3884970f7024bf58a0cc3e6e3cc360f":{
      "scriptId":"u13"},
    "8afab0dd5de74f17b49e6b6017384e45":{
      "scriptId":"u14"},
    "5f91e7aa85944c4e926449fcc68cd42f":{
      "scriptId":"u15"},
    "5735718c715c49408444a9b207f281bf":{
      "scriptId":"u16"},
    "69306aa1844347b081e192cc170dc5a1":{
      "scriptId":"u17"},
    "a9e4bd32185f4d1389c4da6ed9b54e1e":{
      "scriptId":"u18"},
    "9143d9bb53ab4d728b4e12dec01a1cf3":{
      "scriptId":"u19"},
    "77b18015f10e4f2e885cde9eec09bc7c":{
      "scriptId":"u20"},
    "698a5a73221544dfa493fb7f5113bf8f":{
      "scriptId":"u21"},
    "7b06b0397dd84a31bdbaaf0b0f26392b":{
      "scriptId":"u22"},
    "6164af066e9143a8b708145a49cf1922":{
      "scriptId":"u23"},
    "297f582c7c5a41fb9bf3da3d700f039e":{
      "scriptId":"u24"},
    "8c5045385ea84943b02f557595a0ec2b":{
      "scriptId":"u25"},
    "0a10af40b18c473d89e6c2284541a9d6":{
      "scriptId":"u26"},
    "c316c4493235454489e222ed0623d6b7":{
      "scriptId":"u27"},
    "ecbd32c41d6842029b33898b9b1a4910":{
      "scriptId":"u28"},
    "51487ff2a74b48e886d4c29b14fc62d3":{
      "scriptId":"u29"},
    "c5f9ca1cd9354c83b1773467044eac8c":{
      "scriptId":"u30"},
    "39a419116af547f587cd0c8f293c9263":{
      "scriptId":"u31"},
    "d05c07b6886d40f7bbc8c2c8f20e9b54":{
      "scriptId":"u32"},
    "c53d465cfb6a489b9b8e98ac95bb7bf1":{
      "scriptId":"u33"},
    "e6f8fd7680ce4b5c99f2db19aa8609a7":{
      "scriptId":"u34"},
    "64813afe091b40fe96de354aa2302e65":{
      "scriptId":"u35"},
    "78bc13fb135043de87e6d79eefdac2d6":{
      "scriptId":"u36"},
    "60b778368a9949ea913121a7ee13271f":{
      "scriptId":"u37"}}});