$axure.loadCurrentPage({
  "url":"orderlist.html",
  "generationDate":new Date(1594096576478.69),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2cef9f53e4f54bb49a82f4bb0ef6bcb8",
    "type":"Axure:Page",
    "name":"orderlist",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cab68b877fd345728952646203382673",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":412,
              "height":829}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3225d66b459945d3b821db9ff3040119",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":412,
                  "height":829}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orderlist/u0.jpg"}},
{
          "id":"e16a92b4d230472d9081fab6dfc13a4e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":105},
            "size":{
              "width":406,
              "height":700}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"edc65ec5f7bb42f9ab3ac17777fc6fff",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"80d9614a5f4f4ea78c96ea29ea6f4e51",
                  "label":"",
                  "parentDynamicPanel":"e16a92b4d230472d9081fab6dfc13a4e",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":364,
                      "height":1182}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"ecf1dd38e937409a95e6148bd3ac129e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":387,
              "y":105},
            "size":{
              "width":47,
              "height":703}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f57f2e08ef444e8cf5c6e6ee9b0c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":387,
                  "y":105},
                "size":{
                  "width":47,
                  "height":703}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/offerhome/u4.jpg"}},
{
          "id":"c69d80e2b2164a1c8ee8d3f31305a017",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":70},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f1f1d15524cd4414be4d43197e3b2b3a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":70},
            "size":{
              "width":38,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 offerhome",
                      "target":{
                        "targetType":"page",
                        "url":"offerhome.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "cab68b877fd345728952646203382673":{
      "scriptId":"u0"},
    "3225d66b459945d3b821db9ff3040119":{
      "scriptId":"u1"},
    "e16a92b4d230472d9081fab6dfc13a4e":{
      "scriptId":"u2"},
    "80d9614a5f4f4ea78c96ea29ea6f4e51":{
      "scriptId":"u3"},
    "ecf1dd38e937409a95e6148bd3ac129e":{
      "scriptId":"u4"},
    "12f57f2e08ef444e8cf5c6e6ee9b0c11":{
      "scriptId":"u5"},
    "c69d80e2b2164a1c8ee8d3f31305a017":{
      "scriptId":"u6"},
    "f1f1d15524cd4414be4d43197e3b2b3a":{
      "scriptId":"u7"}}});