$axure.loadCurrentPage({
  "url":"dealer_navigation.html",
  "generationDate":new Date(1594096576820.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4b1e970e8c954cbd9abc246f03823229",
    "type":"Axure:Page",
    "name":"dealer_navigation",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7db4e64dc55c42c18a8d5f2ee2b49c89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":413,
              "height":829}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"432a80143ab04c478b44bdeacd28defe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":413,
                  "height":829}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dealer_navigation/u0.jpg"}},
{
          "id":"fa5342973b074a95b09bd419363a77ba",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":126},
            "size":{
              "width":36,
              "height":34}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 orderlist",
                      "target":{
                        "targetType":"page",
                        "url":"orderlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d0b6aa36a9d943e9a032a5e4d68a5a96",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":73},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 pay_successful",
                      "target":{
                        "targetType":"page",
                        "url":"pay_successful.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e1067048116946a8861441649d11e055",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":73},
            "size":{
              "width":32,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7db4e64dc55c42c18a8d5f2ee2b49c89":{
      "scriptId":"u0"},
    "432a80143ab04c478b44bdeacd28defe":{
      "scriptId":"u1"},
    "fa5342973b074a95b09bd419363a77ba":{
      "scriptId":"u2"},
    "d0b6aa36a9d943e9a032a5e4d68a5a96":{
      "scriptId":"u3"},
    "e1067048116946a8861441649d11e055":{
      "scriptId":"u4"}}});