$axure.loadCurrentPage({
  "url":"tyre_details.html",
  "generationDate":new Date(1594096788244.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/tyre_details/bg.jpg",
    "width":414,
    "height":736},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"07a6c147b0c043e09ff45080a4d99428",
    "type":"Axure:Page",
    "name":"tyre_details",
    "notes":{
      "Default":"<p><span style=\"font-family:'Applied Font Regular', 'Applied Font';\">After</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"158c696103cf4f9cb9c9012c82260704",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":289,
              "y":79},
            "size":{
              "width":26,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c3b594ae2ea41f09ef274c62f61dc6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":289,
                  "y":79},
                "size":{
                  "width":26,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 shopcart",
                      "target":{
                        "targetType":"page",
                        "url":"shopcart.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"e7a1dc19b7ea4b10949937657d302be1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":325,
              "y":688},
            "size":{
              "width":74,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4fac9de79ce41e7ad977fbcf4ac92e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":325,
                  "y":688},
                "size":{
                  "width":74,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 generate_order_offshop",
                      "target":{
                        "targetType":"page",
                        "url":"generate_order_offshop.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/tyre_details/u2.png"}},
{
          "id":"c690a72fc93a4200aa145426b94aeb61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":244,
              "y":688},
            "size":{
              "width":74,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd55ce9375ef4cc8b4005510f120c949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":244,
                  "y":688},
                "size":{
                  "width":74,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 generate_order_inshop",
                      "target":{
                        "targetType":"page",
                        "url":"generate_order_inshop.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/tyre_details/u4.png"}},
{
          "id":"cdaab4ae312b4bafa2becdf04dea684c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":163,
              "y":688},
            "size":{
              "width":74,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"064d111c32b74174909f5e5d185c5d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":163,
                  "y":688},
                "size":{
                  "width":74,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shopcart_tip",
                      "objectsToFades":[{
                          "objectPath":["e8e936de0ca64c0793a2a2e50b45ebd5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 shopcart_tip",
                      "objectsToFades":[{
                          "objectPath":["e8e936de0ca64c0793a2a2e50b45ebd5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/tyre_details/u6.png"}},
{
          "id":"e8e936de0ca64c0793a2a2e50b45ebd5",
          "label":"shopcart_tip",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":163,
              "y":650},
            "size":{
              "width":236,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3a27b66dd14b538b4420b8aeacb444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":163,
                  "y":650},
                "size":{
                  "width":236,
                  "height":35},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"344196b1024a4eb490df3d629859811d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":79},
            "size":{
              "width":16,
              "height":23}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 order_list",
                      "target":{
                        "targetType":"page",
                        "url":"order_list.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"06fdc552b4354bbca4de63f4fe6f1936",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":30},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "158c696103cf4f9cb9c9012c82260704":{
      "scriptId":"u0"},
    "8c3b594ae2ea41f09ef274c62f61dc6d":{
      "scriptId":"u1"},
    "e7a1dc19b7ea4b10949937657d302be1":{
      "scriptId":"u2"},
    "b4fac9de79ce41e7ad977fbcf4ac92e5":{
      "scriptId":"u3"},
    "c690a72fc93a4200aa145426b94aeb61":{
      "scriptId":"u4"},
    "cd55ce9375ef4cc8b4005510f120c949":{
      "scriptId":"u5"},
    "cdaab4ae312b4bafa2becdf04dea684c":{
      "scriptId":"u6"},
    "064d111c32b74174909f5e5d185c5d96":{
      "scriptId":"u7"},
    "e8e936de0ca64c0793a2a2e50b45ebd5":{
      "scriptId":"u8"},
    "7c3a27b66dd14b538b4420b8aeacb444":{
      "scriptId":"u9"},
    "344196b1024a4eb490df3d629859811d":{
      "scriptId":"u10"},
    "06fdc552b4354bbca4de63f4fe6f1936":{
      "scriptId":"u11"}}});