$axure.loadCurrentPage({
  "url":"resume_detail_link_internal.html",
  "generationDate":new Date(1594040137661.57),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"119c7d420cbc4def9fcb0bd73027f72b",
    "type":"Axure:Page",
    "name":"resume_detail_link_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"00a368c8c4bd4f228713fe786fe987b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "size":{
              "width":244,
              "height":200},
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"341bf3b6e57349c89728540b654ff205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":244,
                  "height":200},
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/company_detail_link_internal/u0.png"}},
{
          "id":"0578edb0755e4c20913c8f917a760b71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9732a18851ea4e41937f21950d1325a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee1f7cb88fc9426eb4ed1e98a70bf298",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":46},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ccb316092d34d3fad5dcff4ad8451b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":46},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"836fa32c14c348d8962b2c949ae6126c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":74},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0466e84492e4ed990525ea27fb32ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":74},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73121e9e0ee14008af5ae53db5670bae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":101},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72ccc072d8c44d11ab744c4e37daee23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":101},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd21577ab4f34e87a86dbe627c8e6074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF990000,
              "opacity":1},
            "location":{
              "x":20,
              "y":132},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"550abca60e5841a380fb237921edbcef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF990000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":132},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 resume_detail",
                      "target":{
                        "targetType":"page",
                        "url":"resume_detail.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "00a368c8c4bd4f228713fe786fe987b2":{
      "scriptId":"u0"},
    "341bf3b6e57349c89728540b654ff205":{
      "scriptId":"u1"},
    "0578edb0755e4c20913c8f917a760b71":{
      "scriptId":"u2"},
    "9732a18851ea4e41937f21950d1325a8":{
      "scriptId":"u3"},
    "ee1f7cb88fc9426eb4ed1e98a70bf298":{
      "scriptId":"u4"},
    "1ccb316092d34d3fad5dcff4ad8451b2":{
      "scriptId":"u5"},
    "836fa32c14c348d8962b2c949ae6126c":{
      "scriptId":"u6"},
    "f0466e84492e4ed990525ea27fb32ae5":{
      "scriptId":"u7"},
    "73121e9e0ee14008af5ae53db5670bae":{
      "scriptId":"u8"},
    "72ccc072d8c44d11ab744c4e37daee23":{
      "scriptId":"u9"},
    "fd21577ab4f34e87a86dbe627c8e6074":{
      "scriptId":"u10"},
    "550abca60e5841a380fb237921edbcef":{
      "scriptId":"u11"}}});