$axure.loadCurrentPage({
  "url":"company_candidate_search_internal.html",
  "generationDate":new Date(1594040137009.64),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"807f8b6a188f480ab99067051e53b1d5",
    "type":"Axure:Page",
    "name":"company_candidate_search_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c59659ad617e47309a1567f32640addb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":2,
              "y":14},
            "size":{
              "width":188,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1127e0973e04e9cb3a51497b534dc19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":2,
                  "y":14},
                "size":{
                  "width":188,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef1aebf6eaae472f977fe1967ad63d59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":493,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306a2b4ec64e4758982683fae5eb906d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":493,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/company_candidate_search_internal/u2.png"}},
{
          "id":"9bb4bc68d1704bd4abd19680b8c3918e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":8},
            "size":{
              "width":410,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e99d2347454620b43d4df19a90e010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":8},
                "size":{
                  "width":410,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b0437ccf1ee4a1c99a4efe359f93d55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":36},
            "size":{
              "width":430,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec09d2cb0c8d43ed8a82a49ad5cdeceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":36},
                "size":{
                  "width":430,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1936f0c2bc154ba192ef6460662263d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":62},
            "size":{
              "width":399,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e865688175374487aa5d97f3650c0237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":62},
                "size":{
                  "width":399,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9a9e2587db64ebca1a88e836644e580",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":85},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9510564c3f074f5baa28d3f85329d0b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":85},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e468d53a63d4913890b771db33ab9c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":13,
              "y":108},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb85bd00f0e4394b0e0b65fc1157163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":13,
                  "y":108},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9142255c423c4baf8ab10c688a86fe46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":130},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10532a0600a94f4f9ea92e93c1875c3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":130},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c59659ad617e47309a1567f32640addb":{
      "scriptId":"u0"},
    "b1127e0973e04e9cb3a51497b534dc19":{
      "scriptId":"u1"},
    "ef1aebf6eaae472f977fe1967ad63d59":{
      "scriptId":"u2"},
    "306a2b4ec64e4758982683fae5eb906d":{
      "scriptId":"u3"},
    "9bb4bc68d1704bd4abd19680b8c3918e":{
      "scriptId":"u4"},
    "b4e99d2347454620b43d4df19a90e010":{
      "scriptId":"u5"},
    "2b0437ccf1ee4a1c99a4efe359f93d55":{
      "scriptId":"u6"},
    "ec09d2cb0c8d43ed8a82a49ad5cdeceb":{
      "scriptId":"u7"},
    "1936f0c2bc154ba192ef6460662263d3":{
      "scriptId":"u8"},
    "e865688175374487aa5d97f3650c0237":{
      "scriptId":"u9"},
    "f9a9e2587db64ebca1a88e836644e580":{
      "scriptId":"u10"},
    "9510564c3f074f5baa28d3f85329d0b8":{
      "scriptId":"u11"},
    "8e468d53a63d4913890b771db33ab9c4":{
      "scriptId":"u12"},
    "bbb85bd00f0e4394b0e0b65fc1157163":{
      "scriptId":"u13"},
    "9142255c423c4baf8ab10c688a86fe46":{
      "scriptId":"u14"},
    "10532a0600a94f4f9ea92e93c1875c3c":{
      "scriptId":"u15"}}});