$axure.loadCurrentPage({
  "url":"input_resume_step4_basic_info_internal.html",
  "generationDate":new Date(1594040146210.95),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"aeb4b1461b794415ad499d3ff0b616f2",
    "type":"Axure:Page",
    "name":"input_resume_step4_basic_info_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f540bb93a2e046d8a3c8f333d2848670",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":8},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb01c801a8544ec4b54ff8204f27a6b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":8},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68bb1f343b1e4c19a74bd5c410f6485a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":78,
              "y":0},
            "size":{
              "width":260,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1805375843412690037092306458d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":78,
                  "y":0},
                "size":{
                  "width":260,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u4.png"}},
{
          "id":"2264e8ad7cee407f934e0aa8a6975a3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":86,
              "y":8},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372c827649444a88853a27ccd001c759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":86,
                  "y":8},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6785918105b4a0a8867918a2cca3e83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":54},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241c4ed5f723453689e8e3ed74147453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":54},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cfa4d02e7154a4e8482849f4ee97713",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":78,
              "y":46},
            "size":{
              "width":260,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f00a04b94c4cfbac877c8a4f00d0ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":78,
                  "y":46},
                "size":{
                  "width":260,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u4.png"}},
{
          "id":"0a7cbc15daa943c3a47a424691233416",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":3,
              "y":134},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1850469a451647f188c3fbc9630016f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":3,
                  "y":134},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c18233917d7a4b29a815ae53dd6610bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":86,
              "y":52},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1aa6f7877a742c8a3cf0c88dbb9a766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":86,
                  "y":52},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"647f2eb0f75d46dbb83920b41d2a8fe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":94},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00f7b0a1ac6d47b88d3a043985494124",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":94},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08e307b5adad4884835549f01a15dcaa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":78,
              "y":86},
            "size":{
              "width":260,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3fec5d679040a48be21bc7a2937f27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":78,
                  "y":86},
                "size":{
                  "width":260,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u4.png"}},
{
          "id":"883615010250424ca42f9b35a6ef4cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":86,
              "y":94},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b6d03ad562488d9d4e1b6966cbc614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":86,
                  "y":94},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72c8c5ac7ab146f58a07f5df85549bdd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":78,
              "y":128},
            "size":{
              "width":260,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc64bdc851c340a1b58f6e27eb7f1b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":78,
                  "y":128},
                "size":{
                  "width":260,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u4.png"}},
{
          "id":"e199bc8aa2ab47df8265b897dd982446",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":86,
              "y":134},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"899e3c2d5daf43c0ad13957e9c28022a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":86,
                  "y":134},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebe8261418424b188e1f503ebed5cf91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1,
              "y":212},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f03254983f41fa82ba996ee5fd313c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1,
                  "y":212},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20ee849ace6c455f89c3b7165f8e4ab0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":77,
              "y":210},
            "size":{
              "width":610,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b97e0eddcb48da94617aea5122038e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":77,
                  "y":210},
                "size":{
                  "width":610,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_renren_relation/u67.png"}},
{
          "id":"c709a2527add4bfaabb71714bb3c4b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2C3742,
              "opacity":1},
            "location":{
              "x":85,
              "y":212},
            "size":{
              "width":94,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914a157555dd427885319e9811c8dbc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2C3742,
                  "opacity":1},
                "location":{
                  "x":85,
                  "y":212},
                "size":{
                  "width":94,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44bcd44bc4b945e99880435f6ac94d2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1,
              "y":176},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"525a0d9336d24ee7b951686fd6d8083c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1,
                  "y":176},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bccae371a5645a0a6a02c7e72d324ad",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":77,
              "y":170},
            "size":{
              "width":259,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"4824eb381a354b19a216988f5c69a2a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":278},
            "size":{
              "width":256,
              "height":171}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e408c1ed86f466194d4f131ccaa1528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":278},
                "size":{
                  "width":256,
                  "height":171}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_resume_step4_basic_info_internal/u33.jpg"}},
{
          "id":"31ae7effcee9477e8d01e430ae486402",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":266,
              "y":278},
            "size":{
              "width":200,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eee188fd31e44938c1e5a3fdb0a8842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":266,
                  "y":278},
                "size":{
                  "width":200,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_resume_step4_basic_info_internal/u35.jpg"}},
{
          "id":"96aa90e422224a879e020342900b6aaf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":458},
            "size":{
              "width":12,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2a932d560e242e5a824343af7c9f978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":458},
                "size":{
                  "width":12,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/upload_renren_relation/u12.png"}},
{
          "id":"ce54c152959948b29629fd7a1255b87a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":266,
              "y":494},
            "size":{
              "width":12,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9851ab3d1ad4433a86a2b69dfcc7a9dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":266,
                  "y":494},
                "size":{
                  "width":12,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/upload_renren_relation/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f540bb93a2e046d8a3c8f333d2848670":{
      "scriptId":"u0"},
    "eb01c801a8544ec4b54ff8204f27a6b5":{
      "scriptId":"u1"},
    "68bb1f343b1e4c19a74bd5c410f6485a":{
      "scriptId":"u2"},
    "be1805375843412690037092306458d4":{
      "scriptId":"u3"},
    "2264e8ad7cee407f934e0aa8a6975a3c":{
      "scriptId":"u4"},
    "372c827649444a88853a27ccd001c759":{
      "scriptId":"u5"},
    "f6785918105b4a0a8867918a2cca3e83":{
      "scriptId":"u6"},
    "241c4ed5f723453689e8e3ed74147453":{
      "scriptId":"u7"},
    "3cfa4d02e7154a4e8482849f4ee97713":{
      "scriptId":"u8"},
    "c1f00a04b94c4cfbac877c8a4f00d0ab":{
      "scriptId":"u9"},
    "0a7cbc15daa943c3a47a424691233416":{
      "scriptId":"u10"},
    "1850469a451647f188c3fbc9630016f1":{
      "scriptId":"u11"},
    "c18233917d7a4b29a815ae53dd6610bf":{
      "scriptId":"u12"},
    "b1aa6f7877a742c8a3cf0c88dbb9a766":{
      "scriptId":"u13"},
    "647f2eb0f75d46dbb83920b41d2a8fe8":{
      "scriptId":"u14"},
    "00f7b0a1ac6d47b88d3a043985494124":{
      "scriptId":"u15"},
    "08e307b5adad4884835549f01a15dcaa":{
      "scriptId":"u16"},
    "ea3fec5d679040a48be21bc7a2937f27":{
      "scriptId":"u17"},
    "883615010250424ca42f9b35a6ef4cc3":{
      "scriptId":"u18"},
    "20b6d03ad562488d9d4e1b6966cbc614":{
      "scriptId":"u19"},
    "72c8c5ac7ab146f58a07f5df85549bdd":{
      "scriptId":"u20"},
    "dc64bdc851c340a1b58f6e27eb7f1b5e":{
      "scriptId":"u21"},
    "e199bc8aa2ab47df8265b897dd982446":{
      "scriptId":"u22"},
    "899e3c2d5daf43c0ad13957e9c28022a":{
      "scriptId":"u23"},
    "ebe8261418424b188e1f503ebed5cf91":{
      "scriptId":"u24"},
    "02f03254983f41fa82ba996ee5fd313c":{
      "scriptId":"u25"},
    "20ee849ace6c455f89c3b7165f8e4ab0":{
      "scriptId":"u26"},
    "31b97e0eddcb48da94617aea5122038e":{
      "scriptId":"u27"},
    "c709a2527add4bfaabb71714bb3c4b4b":{
      "scriptId":"u28"},
    "914a157555dd427885319e9811c8dbc0":{
      "scriptId":"u29"},
    "44bcd44bc4b945e99880435f6ac94d2e":{
      "scriptId":"u30"},
    "525a0d9336d24ee7b951686fd6d8083c":{
      "scriptId":"u31"},
    "6bccae371a5645a0a6a02c7e72d324ad":{
      "scriptId":"u32"},
    "4824eb381a354b19a216988f5c69a2a4":{
      "scriptId":"u33"},
    "3e408c1ed86f466194d4f131ccaa1528":{
      "scriptId":"u34"},
    "31ae7effcee9477e8d01e430ae486402":{
      "scriptId":"u35"},
    "5eee188fd31e44938c1e5a3fdb0a8842":{
      "scriptId":"u36"},
    "96aa90e422224a879e020342900b6aaf":{
      "scriptId":"u37"},
    "a2a932d560e242e5a824343af7c9f978":{
      "scriptId":"u38"},
    "ce54c152959948b29629fd7a1255b87a":{
      "scriptId":"u39"},
    "9851ab3d1ad4433a86a2b69dfcc7a9dd":{
      "scriptId":"u40"}}});