$axure.loadCurrentPage({
  "url":"wechat_order_picture_detail.html",
  "generationDate":new Date(1594096872828.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d12acc48e762477b8db07287d5fd3c36",
    "type":"Axure:Page",
    "name":"wechat_order_picture_detail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2254d03a42d54e9fba67198e0eb20071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1349,
              "height":1037}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621db83e99cd46b9a8f0549e45bf61d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1349,
                  "height":1037}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wechat_order_picture_detail/u0.png"}},
{
          "id":"25981e8d3a384455b1d54c9878c9826c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "location":{
              "x":223,
              "y":153},
            "size":{
              "width":93,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a62fad566bb544a08772a0bf51179a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "location":{
                  "x":223,
                  "y":153},
                "size":{
                  "width":93,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7636cdf718643bd9b708077a5df9201",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "location":{
              "x":354,
              "y":153},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d78cbe5d3168470c930a8d9051dd26b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "location":{
                  "x":354,
                  "y":153},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c937ac2dabbd410f828f407565b76db2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":224,
              "y":200},
            "size":{
              "width":742,
              "height":743},
            "borderWidth":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10f50eb627448588927a128d5c26350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":224,
                  "y":200},
                "size":{
                  "width":742,
                  "height":743},
                "borderWidth":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 previous_image_arrow,<br>next_image_arrow",
                      "objectsToFades":[{
                          "objectPath":["cd07800e926f40638f48c53df3d7aedd"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e3ea2e00a6874eb89c38c624f4c8eab7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 previous_image_arrow,<br>next_image_arrow",
                      "objectsToFades":[{
                          "objectPath":["cd07800e926f40638f48c53df3d7aedd"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["e3ea2e00a6874eb89c38c624f4c8eab7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/wechat_order_picture_detail/u6.png"}},
{
          "id":"cd07800e926f40638f48c53df3d7aedd",
          "label":"previous_image_arrow",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":247,
              "y":544},
            "size":{
              "width":70,
              "height":70},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1f3cecc9125948d1b556946514cecaea",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"edc5a61f5519446bb73d4f3dbf5b6618",
                  "label":"",
                  "parentDynamicPanel":"cd07800e926f40638f48c53df3d7aedd",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.5",
                    "size":{
                      "width":70,
                      "height":70},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88871b34b9e9445a968e637288cc4db2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cd07800e926f40638f48c53df3d7aedd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "opacity":"0.5",
                        "size":{
                          "width":70,
                          "height":70},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wechat_order_picture_detail/u9.png"}},
{
                  "id":"0b3c1988d0074c1b984febb2fe8a2078",
                  "label":"",
                  "parentDynamicPanel":"cd07800e926f40638f48c53df3d7aedd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"60px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "location":{
                      "x":18,
                      "y":2},
                    "size":{
                      "width":36,
                      "height":68}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1519549efc8f4c8b97f1427bc364bb98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cd07800e926f40638f48c53df3d7aedd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"60px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "location":{
                          "x":18,
                          "y":2},
                        "size":{
                          "width":36,
                          "height":68}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"e3ea2e00a6874eb89c38c624f4c8eab7",
          "label":"next_image_arrow",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":873,
              "y":544},
            "size":{
              "width":70,
              "height":70},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"afc517386b3b421b88bd9dfed1e1482c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f0ad3ba9f48a4d8ab84f3ae41d2f2ea5",
                  "label":"",
                  "parentDynamicPanel":"e3ea2e00a6874eb89c38c624f4c8eab7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.5",
                    "size":{
                      "width":70,
                      "height":70},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"563cd772e97a408094c77e883fc60005",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3ea2e00a6874eb89c38c624f4c8eab7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "opacity":"0.5",
                        "size":{
                          "width":70,
                          "height":70},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/wechat_order_picture_detail/u9.png"}},
{
                  "id":"40be3bf4e500449d8387b4cc61b77346",
                  "label":"",
                  "parentDynamicPanel":"e3ea2e00a6874eb89c38c624f4c8eab7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"60px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "location":{
                      "x":18,
                      "y":2},
                    "size":{
                      "width":36,
                      "height":68}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6b418a7432414c9194cd69f437b58c20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e3ea2e00a6874eb89c38c624f4c8eab7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"60px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "location":{
                          "x":18,
                          "y":2},
                        "size":{
                          "width":36,
                          "height":68}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"75fb5aac0ab94a629a4ac85d42ecc9c9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":100},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 wechat_order_detail",
                      "target":{
                        "targetType":"page",
                        "url":"wechat_order_detail.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"48de3111f47c478184759a232b3e713a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":281},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"face0eea264d4feca629ad8ac66ccdc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":281},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"219e50f5f2004909bb25f4e1d06a3f11",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":278},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 shopcart",
                      "target":{
                        "targetType":"page",
                        "url":"shopcart.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"539934992b694423a6296ec94ccefc10",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":310},
            "size":{
              "width":56,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"62a913a0b1a8402fac45b9dc72e44e4b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":404},
            "size":{
              "width":59,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 dlr_all_orders",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_all_orders.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"072be1be7b66429aa38e276df578af84",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":590},
            "size":{
              "width":59,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 wechat_order_all",
                      "target":{
                        "targetType":"page",
                        "url":"wechat_order_all.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"138d5ef542fe454db1e22f562a87ec52",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":344},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 dlr_order_inprocess",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_order_inprocess.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "2254d03a42d54e9fba67198e0eb20071":{
      "scriptId":"u0"},
    "621db83e99cd46b9a8f0549e45bf61d1":{
      "scriptId":"u1"},
    "25981e8d3a384455b1d54c9878c9826c":{
      "scriptId":"u2"},
    "a62fad566bb544a08772a0bf51179a89":{
      "scriptId":"u3"},
    "d7636cdf718643bd9b708077a5df9201":{
      "scriptId":"u4"},
    "d78cbe5d3168470c930a8d9051dd26b3":{
      "scriptId":"u5"},
    "c937ac2dabbd410f828f407565b76db2":{
      "scriptId":"u6"},
    "a10f50eb627448588927a128d5c26350":{
      "scriptId":"u7"},
    "cd07800e926f40638f48c53df3d7aedd":{
      "scriptId":"u8"},
    "edc5a61f5519446bb73d4f3dbf5b6618":{
      "scriptId":"u9"},
    "88871b34b9e9445a968e637288cc4db2":{
      "scriptId":"u10"},
    "0b3c1988d0074c1b984febb2fe8a2078":{
      "scriptId":"u11"},
    "1519549efc8f4c8b97f1427bc364bb98":{
      "scriptId":"u12"},
    "e3ea2e00a6874eb89c38c624f4c8eab7":{
      "scriptId":"u13"},
    "f0ad3ba9f48a4d8ab84f3ae41d2f2ea5":{
      "scriptId":"u14"},
    "563cd772e97a408094c77e883fc60005":{
      "scriptId":"u15"},
    "40be3bf4e500449d8387b4cc61b77346":{
      "scriptId":"u16"},
    "6b418a7432414c9194cd69f437b58c20":{
      "scriptId":"u17"},
    "75fb5aac0ab94a629a4ac85d42ecc9c9":{
      "scriptId":"u18"},
    "48de3111f47c478184759a232b3e713a":{
      "scriptId":"u19"},
    "face0eea264d4feca629ad8ac66ccdc5":{
      "scriptId":"u20"},
    "219e50f5f2004909bb25f4e1d06a3f11":{
      "scriptId":"u21"},
    "539934992b694423a6296ec94ccefc10":{
      "scriptId":"u22"},
    "62a913a0b1a8402fac45b9dc72e44e4b":{
      "scriptId":"u23"},
    "072be1be7b66429aa38e276df578af84":{
      "scriptId":"u24"},
    "138d5ef542fe454db1e22f562a87ec52":{
      "scriptId":"u25"}}});