$axure.loadCurrentPage({
  "url":"shopcart.html",
  "generationDate":new Date(1594096788319.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/shopcart/bg.jpg",
    "width":414,
    "height":736},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"25e71892ce0b4f00b6ccb5f2913e0421",
    "type":"Axure:Page",
    "name":"shopcart",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11bd4ce398cb4d4e90ac8041f72be048",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":22,
              "y":126},
            "size":{
              "width":296,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ef4850b43e94e1fa195e33c3a3ffede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":126},
                "size":{
                  "width":296,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eb5bc718adf54c2688756db2eda1a55e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":25,
              "y":267},
            "size":{
              "width":213,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6870d18d32d749228516dc45c67c3a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":267},
                "size":{
                  "width":213,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d999122e15de4a4f92ab1a8e764bf093",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":25,
              "y":700},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"789c0a84356e4860ade85e467dfe1708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":700},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4fe862810b4e48219923618dd581c844",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":117,
              "y":153},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ba4dffa8894c63b4527faf6adec87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":117,
                  "y":153},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01476307350641cab50368481c736cc0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":50,
              "y":157},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73314b76cd0d48a8bfc7ac94daa1f857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":157},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9b4c5397a984469a9a8430ef8f6da633",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":698},
            "size":{
              "width":144,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fb5cb4b8ca04b75964fa6a5944597d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":698},
                "size":{
                  "width":144,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e526925deed645d79ec000fa1ac257a0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":50,
              "y":209},
            "size":{
              "width":249,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be34792ea064a23b4eea4a09e0c8f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":209},
                "size":{
                  "width":249,
                  "height":32}},
              "adaptiveStyles":{
}}]},
{
          "id":"c8f86ec0634941cdb7af09d9e66d4a6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":285,
              "y":81},
            "size":{
              "width":20,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b344770ebbb4117a07dab38a9c8b611",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":285,
                  "y":81},
                "size":{
                  "width":20,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 shopcart_editmode",
                      "target":{
                        "targetType":"page",
                        "url":"shopcart_editmode.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shopcart_edit_tip",
                      "objectsToFades":[{
                          "objectPath":["0886e6025d334a26973d7d450142ecd0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 shopcart_edit_tip",
                      "objectsToFades":[{
                          "objectPath":["0886e6025d334a26973d7d450142ecd0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/shopcart/u14.jpg"}},
{
          "id":"18973b772602410884116ac8884cd1f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":244,
              "y":671},
            "size":{
              "width":74,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ec48b511f684072b51a808ed75093be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":244,
                  "y":671},
                "size":{
                  "width":74,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 generate_order_inshop",
                      "target":{
                        "targetType":"page",
                        "url":"generate_order_inshop.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/shopcart/u16.png"}},
{
          "id":"6947bf3dcb1643e6a9a913e79ec3d781",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":325,
              "y":671},
            "size":{
              "width":74,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23903a8de51f45a78e2eb8ebbad78027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":325,
                  "y":671},
                "size":{
                  "width":74,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 generate_order_offshop",
                      "target":{
                        "targetType":"page",
                        "url":"generate_order_offshop.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/shopcart/u18.png"}},
{
          "id":"97a08e1dc1384208bf1c0e3fcd59001d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":327,
              "y":151},
            "size":{
              "width":75,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475ca43450574ba88432d93f76dbed36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":327,
                  "y":151},
                "size":{
                  "width":75,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/shopcart/u20.png"}},
{
          "id":"92ca3af86afa4f41a537409b993f90a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":52,
              "y":183},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29747ad19ead4dc9a36df2b2d61b8354",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":183},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94cd9fa6c3254191813ab68140fab04f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":327,
              "y":200},
            "size":{
              "width":75,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"287661ef26c64044b6e088f6293f20a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":327,
                  "y":200},
                "size":{
                  "width":75,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/shopcart/u20.png"}},
{
          "id":"c593666c99324eecaf7bd61838c67c25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":53,
              "y":234},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f13af685403475d872a8cbcaec1d31f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":234},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f16157bf07ec41c9a393a8b0a33db681",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":49,
              "y":293},
            "size":{
              "width":277,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14234f21ba6245239c80d9a252631686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":293},
                "size":{
                  "width":277,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5b8bf81f958b4576b3bf884a64828c51",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":49,
              "y":345},
            "size":{
              "width":249,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62a5771cff014282b6b32fd274d3ae8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":345},
                "size":{
                  "width":249,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"89c23fe537e54ea6a1d5626418290f53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":326,
              "y":287},
            "size":{
              "width":75,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"551b7c57c4394e7ebccb0e15d6b803fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":326,
                  "y":287},
                "size":{
                  "width":75,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/shopcart/u20.png"}},
{
          "id":"95b6decdf6444916ab23c1d525c0f86f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":51,
              "y":319},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3725c3b79da46389292b839421658a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":319},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28002cd4c3b144bdaf85b3019e1f0483",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":326,
              "y":336},
            "size":{
              "width":75,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bce7d0477da47df81de0a21d5d2a893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":326,
                  "y":336},
                "size":{
                  "width":75,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/shopcart/u20.png"}},
{
          "id":"e37501289c684834ab3abd6d840d5fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099CC,
              "opacity":1},
            "location":{
              "x":52,
              "y":370},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2650f05ebf5e43daacf68e4a4e9627e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":370},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0886e6025d334a26973d7d450142ecd0",
          "label":"shopcart_edit_tip",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":286,
              "y":55},
            "size":{
              "width":124,
              "height":11},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e150f8ef9da45dd9c1d54ac8c6c5161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":55},
                "size":{
                  "width":124,
                  "height":11},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90c1fd77d2554ea19b318c5639fda090",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":81},
            "size":{
              "width":19,
              "height":17}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 order_list",
                      "target":{
                        "targetType":"page",
                        "url":"order_list.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"74040360959648c4840aa6213f270632",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":30},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "11bd4ce398cb4d4e90ac8041f72be048":{
      "scriptId":"u0"},
    "1ef4850b43e94e1fa195e33c3a3ffede":{
      "scriptId":"u1"},
    "eb5bc718adf54c2688756db2eda1a55e":{
      "scriptId":"u2"},
    "6870d18d32d749228516dc45c67c3a69":{
      "scriptId":"u3"},
    "d999122e15de4a4f92ab1a8e764bf093":{
      "scriptId":"u4"},
    "789c0a84356e4860ade85e467dfe1708":{
      "scriptId":"u5"},
    "4fe862810b4e48219923618dd581c844":{
      "scriptId":"u6"},
    "e6ba4dffa8894c63b4527faf6adec87d":{
      "scriptId":"u7"},
    "01476307350641cab50368481c736cc0":{
      "scriptId":"u8"},
    "73314b76cd0d48a8bfc7ac94daa1f857":{
      "scriptId":"u9"},
    "9b4c5397a984469a9a8430ef8f6da633":{
      "scriptId":"u10"},
    "3fb5cb4b8ca04b75964fa6a5944597d2":{
      "scriptId":"u11"},
    "e526925deed645d79ec000fa1ac257a0":{
      "scriptId":"u12"},
    "5be34792ea064a23b4eea4a09e0c8f6a":{
      "scriptId":"u13"},
    "c8f86ec0634941cdb7af09d9e66d4a6f":{
      "scriptId":"u14"},
    "7b344770ebbb4117a07dab38a9c8b611":{
      "scriptId":"u15"},
    "18973b772602410884116ac8884cd1f8":{
      "scriptId":"u16"},
    "4ec48b511f684072b51a808ed75093be":{
      "scriptId":"u17"},
    "6947bf3dcb1643e6a9a913e79ec3d781":{
      "scriptId":"u18"},
    "23903a8de51f45a78e2eb8ebbad78027":{
      "scriptId":"u19"},
    "97a08e1dc1384208bf1c0e3fcd59001d":{
      "scriptId":"u20"},
    "475ca43450574ba88432d93f76dbed36":{
      "scriptId":"u21"},
    "92ca3af86afa4f41a537409b993f90a1":{
      "scriptId":"u22"},
    "29747ad19ead4dc9a36df2b2d61b8354":{
      "scriptId":"u23"},
    "94cd9fa6c3254191813ab68140fab04f":{
      "scriptId":"u24"},
    "287661ef26c64044b6e088f6293f20a6":{
      "scriptId":"u25"},
    "c593666c99324eecaf7bd61838c67c25":{
      "scriptId":"u26"},
    "8f13af685403475d872a8cbcaec1d31f":{
      "scriptId":"u27"},
    "f16157bf07ec41c9a393a8b0a33db681":{
      "scriptId":"u28"},
    "14234f21ba6245239c80d9a252631686":{
      "scriptId":"u29"},
    "5b8bf81f958b4576b3bf884a64828c51":{
      "scriptId":"u30"},
    "62a5771cff014282b6b32fd274d3ae8e":{
      "scriptId":"u31"},
    "89c23fe537e54ea6a1d5626418290f53":{
      "scriptId":"u32"},
    "551b7c57c4394e7ebccb0e15d6b803fa":{
      "scriptId":"u33"},
    "95b6decdf6444916ab23c1d525c0f86f":{
      "scriptId":"u34"},
    "d3725c3b79da46389292b839421658a2":{
      "scriptId":"u35"},
    "28002cd4c3b144bdaf85b3019e1f0483":{
      "scriptId":"u36"},
    "5bce7d0477da47df81de0a21d5d2a893":{
      "scriptId":"u37"},
    "e37501289c684834ab3abd6d840d5fa8":{
      "scriptId":"u38"},
    "2650f05ebf5e43daacf68e4a4e9627e1":{
      "scriptId":"u39"},
    "0886e6025d334a26973d7d450142ecd0":{
      "scriptId":"u40"},
    "1e150f8ef9da45dd9c1d54ac8c6c5161":{
      "scriptId":"u41"},
    "90c1fd77d2554ea19b318c5639fda090":{
      "scriptId":"u42"},
    "74040360959648c4840aa6213f270632":{
      "scriptId":"u43"}}});