$axure.loadCurrentPage({
  "url":"generate_order_offshop_inframe.html",
  "generationDate":new Date(1594096789000.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/generate_order_offshop_inframe/bg.jpg",
    "width":414,
    "height":1550},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"75dbc7b59e2a4a80a0aeb99efc1ddc66",
    "type":"Axure:Page",
    "name":"generate_order_offshop_inframe",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF070616},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7c3150abe814c37aec6e758923cb65b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":14,
              "y":1567},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5291e9fc959946d0b58aecbe93956b1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":1567},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a1437ed87f348d690fee37d29437def",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":1589},
            "size":{
              "width":111,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb68defdb0494d27a8fddd1e104a848d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":1589},
                "size":{
                  "width":111,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u40.jpg"}},
{
          "id":"0e1a9d5f9a404a0bafecfa20b6dab665",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":138,
              "y":1589},
            "size":{
              "width":112,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54647bdb07c24ec1a1c4fdf9315c7fa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":138,
                  "y":1589},
                "size":{
                  "width":112,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u10.jpg"}},
{
          "id":"ed07ed536abd440fb79f88679d530130",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":14,
              "y":1711},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91795bbd4ef54fb1bd4a5624edab75ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":1711},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c14538f23e945f59efae6215932c10e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":1741},
            "size":{
              "width":116,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cedb4131128426e9cca4fca7f4590c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":1741},
                "size":{
                  "width":116,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u16.jpg"}},
{
          "id":"8dc5d8cd7cd54438877abce7b1a95267",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":14,
              "y":1875},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e183bc81f87c4e4dae5c819f9c85a614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":1875},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"427f22f7896b405a84422ff523972698",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":14,
              "y":1907},
            "size":{
              "width":127,
              "height":123}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e687acc45b4c4f8ab2812b2803532f9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":14,
                  "y":1907},
                "size":{
                  "width":127,
                  "height":123}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 tyre_big_picture 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"tyre_big_picture.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/upload_picture_inframe/u30.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "a7c3150abe814c37aec6e758923cb65b":{
      "scriptId":"u0"},
    "5291e9fc959946d0b58aecbe93956b1a":{
      "scriptId":"u1"},
    "8a1437ed87f348d690fee37d29437def":{
      "scriptId":"u2"},
    "cb68defdb0494d27a8fddd1e104a848d":{
      "scriptId":"u3"},
    "0e1a9d5f9a404a0bafecfa20b6dab665":{
      "scriptId":"u4"},
    "54647bdb07c24ec1a1c4fdf9315c7fa3":{
      "scriptId":"u5"},
    "ed07ed536abd440fb79f88679d530130":{
      "scriptId":"u6"},
    "91795bbd4ef54fb1bd4a5624edab75ad":{
      "scriptId":"u7"},
    "5c14538f23e945f59efae6215932c10e":{
      "scriptId":"u8"},
    "3cedb4131128426e9cca4fca7f4590c9":{
      "scriptId":"u9"},
    "8dc5d8cd7cd54438877abce7b1a95267":{
      "scriptId":"u10"},
    "e183bc81f87c4e4dae5c819f9c85a614":{
      "scriptId":"u11"},
    "427f22f7896b405a84422ff523972698":{
      "scriptId":"u12"},
    "e687acc45b4c4f8ab2812b2803532f9c":{
      "scriptId":"u13"}}});