$axure.loadCurrentPage({
  "url":"color_picker2_internal.html",
  "generationDate":new Date(1594040141867.96),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"30c8bee1057b40f9be8d2c185c3cedeb",
    "type":"Axure:Page",
    "name":"color_picker2_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"509023e663b847e69f5890df5f1ff567",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":173,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54bfa99b8f4b450e86e58178955b3535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":173,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/color_picker2_internal/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "509023e663b847e69f5890df5f1ff567":{
      "scriptId":"u0"},
    "54bfa99b8f4b450e86e58178955b3535":{
      "scriptId":"u1"}}});