$axure.loadCurrentPage({
  "url":"merge_company_internal.html",
  "generationDate":new Date(1594040143687.21),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"91becd97ddd84fdba3763529e419456b",
    "type":"Axure:Page",
    "name":"merge_company_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"19e8966ddffb4c3e8f938b8d1546350f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":135,
              "y":110},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47da7a1067124e0a80f9a93198177517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":135,
                  "y":110},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86c684b4d944465b85b2d45141a4ec3f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":210,
              "y":106},
            "size":{
              "width":259,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f93f41f7326b4ab1933bcdf1ebb568cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":134,
              "y":619},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ee2f6e53ae414386b9154121470fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":134,
                  "y":619},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ae638575bf546ef91a8ed06660497ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":209,
              "y":617},
            "size":{
              "width":610,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"509693a0c7594ef3adf24b42b8dca1dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":209,
                  "y":617},
                "size":{
                  "width":610,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_renren_relation/u67.png"}},
{
          "id":"19ced5e04e534f729ca4e39199d7852a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":217,
              "y":624},
            "size":{
              "width":184,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e48d6958ae40478ecfc0b560051ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":624},
                "size":{
                  "width":184,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"227db5a1931541b2bdb9f55955c0ed99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":133,
              "y":486},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86907e979a0e4226b0ae284265ad3e90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":133,
                  "y":486},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16d926a0f1cb4fe0b403613af44fa6ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":133,
              "y":531},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c403a2235d44d7821a918b166d5d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":133,
                  "y":531},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"647055b5443549adbf19791f235264c8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":210,
              "y":526},
            "size":{
              "width":259,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"c55a64b30c4742bfb38c4f410fab5285",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":474,
              "y":536},
            "size":{
              "width":7,
              "height":7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1f4149c51784a6f97da20000db8f745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":474,
                  "y":536},
                "size":{
                  "width":7,
                  "height":7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/upload_renren_relation/u20.png"}},
{
          "id":"5beaafabc2674498a7d6324372335ac3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":209,
              "y":430},
            "size":{
              "width":260,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ed4e87f42e64022a055e9b9ed86d26d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":209,
                  "y":430},
                "size":{
                  "width":260,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u4.png"}},
{
          "id":"d3887a355e1147c1907d07fc635851cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":123,
              "y":436},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af42f7e685174780903e601040094e63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":123,
                  "y":436},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aadabd4cf7041fca1d195e3f7b7c667",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":75,
              "y":313},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c99de60fe8594396bf43b73580ea67e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":75,
                  "y":313},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d263a2eb92845c297f5de60c1dc8323",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":209,
              "y":307},
            "size":{
              "width":259,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"917fa54b6f624801abb3ea278f7f6f79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":75,
              "y":355},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60807a5a42ff4fd4a90fc48cd70c305d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":75,
                  "y":355},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4da7f7afc59349aabf37e644e7d92a8a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":209,
              "y":349},
            "size":{
              "width":259,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"10f49f057479445482783463549e97d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":136,
              "y":153},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760842d5c6b04908a2cc6b45a7d54e98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":136,
                  "y":153},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fafd28398dfa45ba872c16c1a984fdca",
          "label":"alias_text",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":210,
              "y":188},
            "size":{
              "width":259,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bb14c80f90c0457a919609e86a459def",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006633,
              "opacity":1},
            "location":{
              "x":135,
              "y":150},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b6314f7e17f4848b7e8d09fb97ab224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006633,
                  "opacity":1},
                "location":{
                  "x":135,
                  "y":150},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_renren_relation/u79.png"}},
{
          "id":"c0e4f70e76764ac8b4b2d0906c01f50b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006633,
              "opacity":1},
            "location":{
              "x":141,
              "y":148},
            "size":{
              "width":11,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ffe39df17cd40ba9d2d504384cf530b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006633,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":148},
                "size":{
                  "width":11,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca3f4eaea9c4bf3851fafdc48ab9d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":175,
              "y":72},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2304b806d7134bf9b4f72846b93640d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":175,
                  "y":72},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cb0522a416f48698ac857e681d955ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":210,
              "y":72},
            "size":{
              "width":389,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c05354c389884fec8f96f1ec11d79c9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":210,
                  "y":72},
                "size":{
                  "width":389,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"549647a253554a46ae5ac231320db8b7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":210,
              "y":481},
            "size":{
              "width":94,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"1861c5ea254f4aea9887dc5fda150622",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":342,
              "y":481},
            "size":{
              "width":94,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"049b3780a0e04c0fa0225fdbb617e421",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":309,
              "y":485},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94b9e523c62541c7a981f4d9f1743128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":309,
                  "y":485},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5db06a2801ae4e52905eea64f69e000e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":445,
              "y":485},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27438a93937c471ab36d10c23f230074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":445,
                  "y":485},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e360bfc32704c97b9b17971701cd38c",
          "label":"alias_label",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":154,
              "y":192},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df72cb410af64553818bef8179c4e394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":154,
                  "y":192},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1edc471e61c64e409dd217570ea28107",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":136,
              "y":239},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10f467beb0664e98952e7895f6bdfc38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":136,
                  "y":239},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cafa104c3b44e95948550ce28bd65e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006633,
              "opacity":1},
            "location":{
              "x":135,
              "y":236},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3250a7f18688485493d56680e6e71b19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006633,
                  "opacity":1},
                "location":{
                  "x":135,
                  "y":236},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_renren_relation/u79.png"}},
{
          "id":"02b796f8f7664c36a2b06863dbe68b12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006633,
              "opacity":1},
            "location":{
              "x":141,
              "y":234},
            "size":{
              "width":11,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95b7e35039ff4463b43436a0d951b919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006633,
                  "opacity":1},
                "location":{
                  "x":141,
                  "y":234},
                "size":{
                  "width":11,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a0e4ef2b79e416188a248615e48542e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":138,
              "y":395},
            "size":{
              "width":138,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a1686ed59a34c908d4173ee06b408f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":138,
                  "y":395},
                "size":{
                  "width":138,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8743cc2b82fe4ad0aba4ad0a3ab25eed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006633,
              "opacity":1},
            "location":{
              "x":136,
              "y":392},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF006600},
            "cornerRadiusTopLeft":"11"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a99a3f22a004a86b9cd477f4e3953ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006633,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":392},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF006600},
                "cornerRadiusTopLeft":"11"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/input_renren_relation/u79.png"}},
{
          "id":"a6f1d601eb994736a27696d6a68d45fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006633,
              "opacity":1},
            "location":{
              "x":142,
              "y":390},
            "size":{
              "width":11,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e270f93991cf457c823031458a971218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006633,
                  "opacity":1},
                "location":{
                  "x":142,
                  "y":390},
                "size":{
                  "width":11,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db054113cf6241ef817922608d9052da",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":138,
              "y":277},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f741f1c1a71146989b4ab9d83f1046fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":138,
                  "y":277},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"98cae9afae0a4d7f949f4bbef695f213",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":133,
              "y":577},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c92ee044a3804ce597681ad23fcf271a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":133,
                  "y":577},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"198baa65c9374a42bc0bc0c3c9849650",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":210,
              "y":570},
            "size":{
              "width":260,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af6da2dd3d44f8bbb848f8687c85c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":210,
                  "y":570},
                "size":{
                  "width":260,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u4.png"}},
{
          "id":"f85c96c0045d4db2903f3c33ba44902c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":218,
              "y":577},
            "size":{
              "width":234,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d905eee94f924c34a0b46d1feed39838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":577},
                "size":{
                  "width":234,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dafc32573eba4784890aab824a6570c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":217,
              "y":437},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ff4302746841a490547e11eb86aca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":217,
                  "y":437},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a680180c19a47cda578ccb397fe2821",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":804},
            "size":{
              "width":1260,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2741d90d43c14f769c3f26a2383e8609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":804},
                "size":{
                  "width":1260,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/u36.png"}},
{
          "id":"2ce340a4adbb4cfb8a9a08c7af621a93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF2C3742},
            "location":{
              "x":200,
              "y":18},
            "size":{
              "width":84,
              "height":30},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1143d8c8346948a8a18ef77e42803c35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2C3742},
                "location":{
                  "x":200,
                  "y":18},
                "size":{
                  "width":84,
                  "height":30},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 uploadCompanyPopup = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"uploadCompanyPopup"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 upload_company_info 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"upload_company_info.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/merge_company_internal/u69.png"}},
{
          "id":"670246c5abad4d619896d2eb93f7acc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF2C3742},
            "location":{
              "x":313,
              "y":18},
            "size":{
              "width":84,
              "height":30},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"045f026f017446b695e345d263f64138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2C3742},
                "location":{
                  "x":313,
                  "y":18},
                "size":{
                  "width":84,
                  "height":30},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 uploadCompanyPopup = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"uploadCompanyPopup"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 upload_company_info 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"upload_company_info.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/merge_company_internal/u69.png"}},
{
          "id":"d8bb10f62e364ab6b37d04707b4bbc3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF2C3742},
            "location":{
              "x":200,
              "y":739},
            "size":{
              "width":84,
              "height":30},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db07635081af419fa8efaf7623e2e27e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2C3742},
                "location":{
                  "x":200,
                  "y":739},
                "size":{
                  "width":84,
                  "height":30},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 uploadCompanyPopup = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"uploadCompanyPopup"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 upload_company_info 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"upload_company_info.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/merge_company_internal/u69.png"}},
{
          "id":"9a667b9e82814c598fd0513fddc9ec4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF7F7F7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF2C3742},
            "location":{
              "x":313,
              "y":739},
            "size":{
              "width":84,
              "height":30},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc59793dd9b04d589fb00c3a9358e669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF7F7F7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2C3742},
                "location":{
                  "x":313,
                  "y":739},
                "size":{
                  "width":84,
                  "height":30},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 uploadCompanyPopup = &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"uploadCompanyPopup"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 upload_company_info 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"upload_company_info.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/merge_company_internal/u69.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "19e8966ddffb4c3e8f938b8d1546350f":{
      "scriptId":"u0"},
    "47da7a1067124e0a80f9a93198177517":{
      "scriptId":"u1"},
    "86c684b4d944465b85b2d45141a4ec3f":{
      "scriptId":"u2"},
    "f93f41f7326b4ab1933bcdf1ebb568cc":{
      "scriptId":"u3"},
    "76ee2f6e53ae414386b9154121470fac":{
      "scriptId":"u4"},
    "5ae638575bf546ef91a8ed06660497ac":{
      "scriptId":"u5"},
    "509693a0c7594ef3adf24b42b8dca1dd":{
      "scriptId":"u6"},
    "19ced5e04e534f729ca4e39199d7852a":{
      "scriptId":"u7"},
    "35e48d6958ae40478ecfc0b560051ff6":{
      "scriptId":"u8"},
    "227db5a1931541b2bdb9f55955c0ed99":{
      "scriptId":"u9"},
    "86907e979a0e4226b0ae284265ad3e90":{
      "scriptId":"u10"},
    "16d926a0f1cb4fe0b403613af44fa6ef":{
      "scriptId":"u11"},
    "78c403a2235d44d7821a918b166d5d19":{
      "scriptId":"u12"},
    "647055b5443549adbf19791f235264c8":{
      "scriptId":"u13"},
    "c55a64b30c4742bfb38c4f410fab5285":{
      "scriptId":"u14"},
    "e1f4149c51784a6f97da20000db8f745":{
      "scriptId":"u15"},
    "5beaafabc2674498a7d6324372335ac3":{
      "scriptId":"u16"},
    "0ed4e87f42e64022a055e9b9ed86d26d":{
      "scriptId":"u17"},
    "d3887a355e1147c1907d07fc635851cd":{
      "scriptId":"u18"},
    "af42f7e685174780903e601040094e63":{
      "scriptId":"u19"},
    "1aadabd4cf7041fca1d195e3f7b7c667":{
      "scriptId":"u20"},
    "c99de60fe8594396bf43b73580ea67e9":{
      "scriptId":"u21"},
    "8d263a2eb92845c297f5de60c1dc8323":{
      "scriptId":"u22"},
    "917fa54b6f624801abb3ea278f7f6f79":{
      "scriptId":"u23"},
    "60807a5a42ff4fd4a90fc48cd70c305d":{
      "scriptId":"u24"},
    "4da7f7afc59349aabf37e644e7d92a8a":{
      "scriptId":"u25"},
    "10f49f057479445482783463549e97d9":{
      "scriptId":"u26"},
    "760842d5c6b04908a2cc6b45a7d54e98":{
      "scriptId":"u27"},
    "fafd28398dfa45ba872c16c1a984fdca":{
      "scriptId":"u28"},
    "bb14c80f90c0457a919609e86a459def":{
      "scriptId":"u29"},
    "3b6314f7e17f4848b7e8d09fb97ab224":{
      "scriptId":"u30"},
    "c0e4f70e76764ac8b4b2d0906c01f50b":{
      "scriptId":"u31"},
    "2ffe39df17cd40ba9d2d504384cf530b":{
      "scriptId":"u32"},
    "0ca3f4eaea9c4bf3851fafdc48ab9d01":{
      "scriptId":"u33"},
    "2304b806d7134bf9b4f72846b93640d4":{
      "scriptId":"u34"},
    "7cb0522a416f48698ac857e681d955ac":{
      "scriptId":"u35"},
    "c05354c389884fec8f96f1ec11d79c9f":{
      "scriptId":"u36"},
    "549647a253554a46ae5ac231320db8b7":{
      "scriptId":"u37"},
    "1861c5ea254f4aea9887dc5fda150622":{
      "scriptId":"u38"},
    "049b3780a0e04c0fa0225fdbb617e421":{
      "scriptId":"u39"},
    "94b9e523c62541c7a981f4d9f1743128":{
      "scriptId":"u40"},
    "5db06a2801ae4e52905eea64f69e000e":{
      "scriptId":"u41"},
    "27438a93937c471ab36d10c23f230074":{
      "scriptId":"u42"},
    "8e360bfc32704c97b9b17971701cd38c":{
      "scriptId":"u43"},
    "df72cb410af64553818bef8179c4e394":{
      "scriptId":"u44"},
    "1edc471e61c64e409dd217570ea28107":{
      "scriptId":"u45"},
    "10f467beb0664e98952e7895f6bdfc38":{
      "scriptId":"u46"},
    "6cafa104c3b44e95948550ce28bd65e9":{
      "scriptId":"u47"},
    "3250a7f18688485493d56680e6e71b19":{
      "scriptId":"u48"},
    "02b796f8f7664c36a2b06863dbe68b12":{
      "scriptId":"u49"},
    "95b7e35039ff4463b43436a0d951b919":{
      "scriptId":"u50"},
    "6a0e4ef2b79e416188a248615e48542e":{
      "scriptId":"u51"},
    "9a1686ed59a34c908d4173ee06b408f3":{
      "scriptId":"u52"},
    "8743cc2b82fe4ad0aba4ad0a3ab25eed":{
      "scriptId":"u53"},
    "7a99a3f22a004a86b9cd477f4e3953ac":{
      "scriptId":"u54"},
    "a6f1d601eb994736a27696d6a68d45fb":{
      "scriptId":"u55"},
    "e270f93991cf457c823031458a971218":{
      "scriptId":"u56"},
    "db054113cf6241ef817922608d9052da":{
      "scriptId":"u57"},
    "f741f1c1a71146989b4ab9d83f1046fe":{
      "scriptId":"u58"},
    "98cae9afae0a4d7f949f4bbef695f213":{
      "scriptId":"u59"},
    "c92ee044a3804ce597681ad23fcf271a":{
      "scriptId":"u60"},
    "198baa65c9374a42bc0bc0c3c9849650":{
      "scriptId":"u61"},
    "3af6da2dd3d44f8bbb848f8687c85c4a":{
      "scriptId":"u62"},
    "f85c96c0045d4db2903f3c33ba44902c":{
      "scriptId":"u63"},
    "d905eee94f924c34a0b46d1feed39838":{
      "scriptId":"u64"},
    "dafc32573eba4784890aab824a6570c3":{
      "scriptId":"u65"},
    "e6ff4302746841a490547e11eb86aca3":{
      "scriptId":"u66"},
    "5a680180c19a47cda578ccb397fe2821":{
      "scriptId":"u67"},
    "2741d90d43c14f769c3f26a2383e8609":{
      "scriptId":"u68"},
    "2ce340a4adbb4cfb8a9a08c7af621a93":{
      "scriptId":"u69"},
    "1143d8c8346948a8a18ef77e42803c35":{
      "scriptId":"u70"},
    "670246c5abad4d619896d2eb93f7acc6":{
      "scriptId":"u71"},
    "045f026f017446b695e345d263f64138":{
      "scriptId":"u72"},
    "d8bb10f62e364ab6b37d04707b4bbc3c":{
      "scriptId":"u73"},
    "db07635081af419fa8efaf7623e2e27e":{
      "scriptId":"u74"},
    "9a667b9e82814c598fd0513fddc9ec4e":{
      "scriptId":"u75"},
    "cc59793dd9b04d589fb00c3a9358e669":{
      "scriptId":"u76"}}});