$axure.loadCurrentPage({
  "url":"dlr_order_inframe.html",
  "generationDate":new Date(1594096872918.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a503dd1f33024c64a5453b3f6b57ae0e",
    "type":"Axure:Page",
    "name":"dlr_order_inframe",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c1c3b64b345942bc8b22af1fe309331a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":1510,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dlr_order_inframe/u0_line.png"}},
{
          "id":"e59d4ca75aaa40a0a818ad57832a46e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":22,
              "y":29},
            "size":{
              "width":32,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8ed1b959f04d139f1d76f38307f106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":29},
                "size":{
                  "width":32,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c6139db7ddb4260b6b9476b9adafabc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":103,
              "y":29},
            "size":{
              "width":52,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d8bbd688f0f4d8ca5a253d201cf6a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":29},
                "size":{
                  "width":52,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c54b7675ff44d6aa04eae1949dbff15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":283,
              "y":29},
            "size":{
              "width":70,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"664bebee117d4d299190036b16e55425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":29},
                "size":{
                  "width":70,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1180ca24779946a0826477d1e9946015",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":370,
              "y":29},
            "size":{
              "width":110,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8e4b11d98bb42ab866125b49136185c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":29},
                "size":{
                  "width":110,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d5e85f4db46489c91342dc75fa17119",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":494,
              "y":29},
            "size":{
              "width":110,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f6f65571be41e5a9ca90b84bfbf2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":29},
                "size":{
                  "width":110,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93f19cb4a65241a799db13aac8345d70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":580,
              "y":29},
            "size":{
              "width":54,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82a29bcc1e344a6a1631c23871923a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":29},
                "size":{
                  "width":54,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a8b47acc9f545f78f5aa12af8aee767",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":678,
              "y":29},
            "size":{
              "width":32,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e8eeba21e59487ca38f69b58a4616a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":678,
                  "y":29},
                "size":{
                  "width":32,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b9f45968b854dca946a15ccf9198221",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":744,
              "y":29},
            "size":{
              "width":34,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"894c917ed30a4667ae433d0ff60405be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":744,
                  "y":29},
                "size":{
                  "width":34,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"162787c133a042bab130f7fd2a9ed2c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":825,
              "y":29},
            "size":{
              "width":72,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78b3627efe094ebfa85eaecfba88e67a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":825,
                  "y":29},
                "size":{
                  "width":72,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cea112a36fda4b8499c0edddbc6175a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":907,
              "y":29},
            "size":{
              "width":38,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d960a74e89a64973bb109d0f0c3437d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":907,
                  "y":29},
                "size":{
                  "width":38,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e0d36e032704cb18695cfac0b05fd21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":1105,
              "y":29},
            "size":{
              "width":40,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7acaebb64f484ca81e42abec8c2047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":1105,
                  "y":29},
                "size":{
                  "width":40,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f3990daf5dc44a8a8a7f9b3093f57d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":1155,
              "y":29},
            "size":{
              "width":40,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f0dcdcdd9984b15936a77454ef79588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":1155,
                  "y":29},
                "size":{
                  "width":40,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21682a0168ff4e70aff85cad31d9792f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":1226,
              "y":29},
            "size":{
              "width":70,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba276440bffc484f8b14f7a4da20112f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":1226,
                  "y":29},
                "size":{
                  "width":70,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c6d88bc5eb1450cb062a14a33398976",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":1306,
              "y":29},
            "size":{
              "width":140,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc41b7e9436541a2907788d6a7eb2755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":1306,
                  "y":29},
                "size":{
                  "width":140,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a616674cbb3474a97e7f210db2ce38e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":1466,
              "y":28},
            "size":{
              "width":76,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfbf33625ebf4f6c9e31e3c1910dad28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":1466,
                  "y":28},
                "size":{
                  "width":76,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cfe93938d414d3c95893a943e911119",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":21,
              "y":66},
            "size":{
              "width":51,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c1fffcc38c34c0185cf99859667a632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":21,
                  "y":66},
                "size":{
                  "width":51,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 dlr_order_details1 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_order_details1.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dlr_order_inframe/u31.png"}},
{
          "id":"6bbd22501cfa49f49c49659fa5fa26f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CCCC,
              "opacity":1},
            "location":{
              "x":103,
              "y":73},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b34772e3c9e54fbcb0c2502683ef9ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CCCC,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":73},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"791ed9d2f0854056a7561dfd1d54ef16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":370,
              "y":72},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4fadfc18c344855bc689038a844e049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":72},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1c0b446a60c4cf8b871706f934fa414",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":495,
              "y":71},
            "size":{
              "width":25,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4821a345504dbf9bcad660f7811167",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":495,
                  "y":71},
                "size":{
                  "width":25,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74df5eeac81f4e77a45825ea8f0ff87a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":580,
              "y":70},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab17ffc629764737a59bc2be8fb381ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":580,
                  "y":70},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fe716dc5a9046488c2f969459b591b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":679,
              "y":69},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4609982f91074998a4e45d6727f28066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":679,
                  "y":69},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"399bad81787d43d7918cfa132320c7b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":744,
              "y":68},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c87c603983c4f21958758f6f227a0f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":744,
                  "y":68},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"270ddf0be8734518b7c5656d74c5f971",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":826,
              "y":67},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc90187e2d44ce29c08bbc2802f9238",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":826,
                  "y":67},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbd73829e5cb4c9fb88c527c45b20761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":909,
              "y":66},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d428df76e81d41eb94258ae1e7585609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":909,
                  "y":66},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2368d3542731405facd006f8608d167b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1108,
              "y":66},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a458086c1c346b2b4d3f2e7d79eaea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1108,
                  "y":66},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b51afe2183014fdbbe712584095e0c08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1156,
              "y":66},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29d6f3f83d9743d5b2b41f3c92901243",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1156,
                  "y":66},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a731182d8982469b97527e2ef5d0bc11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1229,
              "y":65},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e00f85cd9b4412a0ae07283eb472db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1229,
                  "y":65},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5e0e45d39a54bbf9c57031b15424074",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CCCC,
              "opacity":1},
            "location":{
              "x":1306,
              "y":66},
            "size":{
              "width":129,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a61635325d654d9d89452d4af8ddb15d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CCCC,
                  "opacity":1},
                "location":{
                  "x":1306,
                  "y":66},
                "size":{
                  "width":129,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf91f8666a3f4095871492f202b427a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1466,
              "y":66},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"232199c5c29f4cc498a0d8821e548eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1466,
                  "y":66},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"483c4d0226964b59974da23740998fac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":580,
              "y":105},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fbeef1dac90400498ecdddde6d8bc0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":580,
                  "y":105},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b0c7e126289483f87a0973909defa87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":679,
              "y":104},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0fb0fc84e384f25823b2afd8ebe97c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":679,
                  "y":104},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a3d50d70db74d43a4e1ddd232f5cc0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":744,
              "y":103},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"175132cfcb614bc2961990ac8b2520c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":744,
                  "y":103},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fba6f25556b84ad0a6a57a2d12390f07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":826,
              "y":102},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e8133f0a4e4603a55dc540e313185e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":826,
                  "y":102},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c308c5ffd6fc41f1b73e7367db1d5ce0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":909,
              "y":101},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e8974c29363434aa1ffd51bbcf37518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":909,
                  "y":101},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c389cfff867e41dd9a788fe94555293b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1108,
              "y":101},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c9f2d1e4564e6dae30298dba321e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1108,
                  "y":101},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6122ad8e73e249948b28919f8a9c0bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1156,
              "y":101},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946312a4ea204459948bc12cf8520190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1156,
                  "y":101},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62159c265c764f8aa98c84c4b01ee13f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1229,
              "y":100},
            "size":{
              "width":55,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff5ff889a0484ac99cade352e895e88f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1229,
                  "y":100},
                "size":{
                  "width":55,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f80e81f5db641c88653c8e660f618d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1466,
              "y":101},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"352289d9f10d41bd8267152c046105f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1466,
                  "y":101},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"694e25a960f04e889e5431864647834c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":133},
            "size":{
              "width":1510,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dlr_order_inframe/u77_line.png"}},
{
          "id":"408c238065a44b7c9f05091be5a5d2f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":21,
              "y":148},
            "size":{
              "width":51,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f86168c56ee74a598b738ccc5f87304b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":21,
                  "y":148},
                "size":{
                  "width":51,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 dlr_order_details2 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_order_details2.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dlr_order_inframe/u31.png"}},
{
          "id":"b303f005fbbe4b9ea775d5655c756e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CCCC,
              "opacity":1},
            "location":{
              "x":103,
              "y":155},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20837be443444959bff9b5337a9964ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CCCC,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":155},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2231c03d95714df090addfe3ee70d53e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":370,
              "y":154},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7dcdf8f5654b6499778b6f22287a9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":154},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c48de03d00bf4056b4e61e8a7abe0e72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":495,
              "y":153},
            "size":{
              "width":25,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a179cff963a453aa5f7a553f2f79c25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":495,
                  "y":153},
                "size":{
                  "width":25,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d36b887eab7148b582c80ce3d316aa24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":580,
              "y":152},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99de3c358579431ea86da57699b4c1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":580,
                  "y":152},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4411f8de2de448f5bb75ca61431bd35e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":679,
              "y":151},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ec8fd1c906644ff8bdcfaa4ec1f5ce9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":679,
                  "y":151},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ce87abdbf834cbe966d7f6bd2584f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":744,
              "y":150},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68c00f2b6902493c928914a848aaa791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":744,
                  "y":150},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d8d6164b5b844a5b436abf62931b386",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":826,
              "y":149},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7385e63590a44ebb8119573cf2b7c46a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":826,
                  "y":149},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48e45ed3b7ca451faa535489cdcffa6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":909,
              "y":148},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43d5d619eae44cee93b9c5eb373f3cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":909,
                  "y":148},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4ee72283b8b46b9bf1e04d105a4556a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1108,
              "y":148},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85a1738b4026428bb0f18e21ca836b52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1108,
                  "y":148},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df37f18f551f48dcae5d8dab9f047180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1156,
              "y":148},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a3f54ec02ff4c23869179e609de6d7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1156,
                  "y":148},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"409fb0042ee34a9ca1328ff02a2697d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1229,
              "y":147},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"610b1cc4f9e649d3a0ce74a32feb48e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1229,
                  "y":147},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e754adfaa0e4ab394d122c3594cf985",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66CCCC,
              "opacity":1},
            "location":{
              "x":1306,
              "y":148},
            "size":{
              "width":129,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd8795086a1437ca8b4e6769e174c61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66CCCC,
                  "opacity":1},
                "location":{
                  "x":1306,
                  "y":148},
                "size":{
                  "width":129,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a03c4081be54772ba478a9ad09b74f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1466,
              "y":148},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60e1ff7a53454c158b011b1f09c5847f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1466,
                  "y":148},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95ebcf35c00d4685a07f820c7fa7dfad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":580,
              "y":187},
            "size":{
              "width":80,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd8c228b1ac54b0a8ff470e268575ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":580,
                  "y":187},
                "size":{
                  "width":80,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d994d469142d4b45a4ccd1621068f043",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":679,
              "y":186},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27a490ef18914b5fa6d6660d7fdca8a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":679,
                  "y":186},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4302d5e8f364cf3a881065a2834a1d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":744,
              "y":185},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e1079b9ba6c45acacd0e3048373905c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":744,
                  "y":185},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f09c6ff77624ad9af4d7ed39d2ac7e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":826,
              "y":184},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8796ca829ac746b3b8439b2692eb3c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":826,
                  "y":184},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c435706701c744158e80904c0f2679df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":909,
              "y":183},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cab3bd420d44faaac10bb8ddff1948b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":909,
                  "y":183},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"436f0beed9e14e3d9a3db69046518e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1108,
              "y":183},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f78189e960e54537899bcfb89f0875b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1108,
                  "y":183},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71fa6a54e5d346b2907b59cdc7cc0b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1156,
              "y":183},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e0e8163fd940428b2585359a777bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1156,
                  "y":183},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44409bce5ebb495ba6c742049dbfdfb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1229,
              "y":182},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92120f3330f244928bb4e04120b8f10d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1229,
                  "y":182},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c93a4195ea754623b38bd2879f74693a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1466,
              "y":183},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0b18a51c4e4e3a883d2c18920fa6cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1466,
                  "y":183},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fee1784081ba49918861263a5a01d74a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":211},
            "size":{
              "width":1510,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDBDBDB}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dlr_order_inframe/u77_line.png"}},
{
          "id":"8c6a9f64a7a44d3a9d68c5c725d34743",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":72},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 dlr_order_details1 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_order_details1.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true},
{
          "id":"870dec2f1c484f3baf787b786361e4b3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":155},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 dlr_order_details2 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"dlr_order_details2.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "c1c3b64b345942bc8b22af1fe309331a":{
      "scriptId":"u0"},
    "e59d4ca75aaa40a0a818ad57832a46e6":{
      "scriptId":"u1"},
    "eb8ed1b959f04d139f1d76f38307f106":{
      "scriptId":"u2"},
    "0c6139db7ddb4260b6b9476b9adafabc":{
      "scriptId":"u3"},
    "7d8bbd688f0f4d8ca5a253d201cf6a1e":{
      "scriptId":"u4"},
    "6c54b7675ff44d6aa04eae1949dbff15":{
      "scriptId":"u5"},
    "664bebee117d4d299190036b16e55425":{
      "scriptId":"u6"},
    "1180ca24779946a0826477d1e9946015":{
      "scriptId":"u7"},
    "d8e4b11d98bb42ab866125b49136185c":{
      "scriptId":"u8"},
    "0d5e85f4db46489c91342dc75fa17119":{
      "scriptId":"u9"},
    "73f6f65571be41e5a9ca90b84bfbf2d7":{
      "scriptId":"u10"},
    "93f19cb4a65241a799db13aac8345d70":{
      "scriptId":"u11"},
    "f82a29bcc1e344a6a1631c23871923a7":{
      "scriptId":"u12"},
    "6a8b47acc9f545f78f5aa12af8aee767":{
      "scriptId":"u13"},
    "7e8eeba21e59487ca38f69b58a4616a8":{
      "scriptId":"u14"},
    "0b9f45968b854dca946a15ccf9198221":{
      "scriptId":"u15"},
    "894c917ed30a4667ae433d0ff60405be":{
      "scriptId":"u16"},
    "162787c133a042bab130f7fd2a9ed2c0":{
      "scriptId":"u17"},
    "78b3627efe094ebfa85eaecfba88e67a":{
      "scriptId":"u18"},
    "cea112a36fda4b8499c0edddbc6175a3":{
      "scriptId":"u19"},
    "d960a74e89a64973bb109d0f0c3437d5":{
      "scriptId":"u20"},
    "0e0d36e032704cb18695cfac0b05fd21":{
      "scriptId":"u21"},
    "9f7acaebb64f484ca81e42abec8c2047":{
      "scriptId":"u22"},
    "2f3990daf5dc44a8a8a7f9b3093f57d7":{
      "scriptId":"u23"},
    "8f0dcdcdd9984b15936a77454ef79588":{
      "scriptId":"u24"},
    "21682a0168ff4e70aff85cad31d9792f":{
      "scriptId":"u25"},
    "ba276440bffc484f8b14f7a4da20112f":{
      "scriptId":"u26"},
    "2c6d88bc5eb1450cb062a14a33398976":{
      "scriptId":"u27"},
    "dc41b7e9436541a2907788d6a7eb2755":{
      "scriptId":"u28"},
    "6a616674cbb3474a97e7f210db2ce38e":{
      "scriptId":"u29"},
    "cfbf33625ebf4f6c9e31e3c1910dad28":{
      "scriptId":"u30"},
    "3cfe93938d414d3c95893a943e911119":{
      "scriptId":"u31"},
    "7c1fffcc38c34c0185cf99859667a632":{
      "scriptId":"u32"},
    "6bbd22501cfa49f49c49659fa5fa26f9":{
      "scriptId":"u33"},
    "b34772e3c9e54fbcb0c2502683ef9ec1":{
      "scriptId":"u34"},
    "791ed9d2f0854056a7561dfd1d54ef16":{
      "scriptId":"u35"},
    "e4fadfc18c344855bc689038a844e049":{
      "scriptId":"u36"},
    "f1c0b446a60c4cf8b871706f934fa414":{
      "scriptId":"u37"},
    "4e4821a345504dbf9bcad660f7811167":{
      "scriptId":"u38"},
    "74df5eeac81f4e77a45825ea8f0ff87a":{
      "scriptId":"u39"},
    "ab17ffc629764737a59bc2be8fb381ae":{
      "scriptId":"u40"},
    "1fe716dc5a9046488c2f969459b591b3":{
      "scriptId":"u41"},
    "4609982f91074998a4e45d6727f28066":{
      "scriptId":"u42"},
    "399bad81787d43d7918cfa132320c7b3":{
      "scriptId":"u43"},
    "7c87c603983c4f21958758f6f227a0f5":{
      "scriptId":"u44"},
    "270ddf0be8734518b7c5656d74c5f971":{
      "scriptId":"u45"},
    "bfc90187e2d44ce29c08bbc2802f9238":{
      "scriptId":"u46"},
    "cbd73829e5cb4c9fb88c527c45b20761":{
      "scriptId":"u47"},
    "d428df76e81d41eb94258ae1e7585609":{
      "scriptId":"u48"},
    "2368d3542731405facd006f8608d167b":{
      "scriptId":"u49"},
    "9a458086c1c346b2b4d3f2e7d79eaea0":{
      "scriptId":"u50"},
    "b51afe2183014fdbbe712584095e0c08":{
      "scriptId":"u51"},
    "29d6f3f83d9743d5b2b41f3c92901243":{
      "scriptId":"u52"},
    "a731182d8982469b97527e2ef5d0bc11":{
      "scriptId":"u53"},
    "76e00f85cd9b4412a0ae07283eb472db":{
      "scriptId":"u54"},
    "a5e0e45d39a54bbf9c57031b15424074":{
      "scriptId":"u55"},
    "a61635325d654d9d89452d4af8ddb15d":{
      "scriptId":"u56"},
    "bf91f8666a3f4095871492f202b427a9":{
      "scriptId":"u57"},
    "232199c5c29f4cc498a0d8821e548eec":{
      "scriptId":"u58"},
    "483c4d0226964b59974da23740998fac":{
      "scriptId":"u59"},
    "5fbeef1dac90400498ecdddde6d8bc0e":{
      "scriptId":"u60"},
    "0b0c7e126289483f87a0973909defa87":{
      "scriptId":"u61"},
    "e0fb0fc84e384f25823b2afd8ebe97c3":{
      "scriptId":"u62"},
    "6a3d50d70db74d43a4e1ddd232f5cc0a":{
      "scriptId":"u63"},
    "175132cfcb614bc2961990ac8b2520c2":{
      "scriptId":"u64"},
    "fba6f25556b84ad0a6a57a2d12390f07":{
      "scriptId":"u65"},
    "43e8133f0a4e4603a55dc540e313185e":{
      "scriptId":"u66"},
    "c308c5ffd6fc41f1b73e7367db1d5ce0":{
      "scriptId":"u67"},
    "6e8974c29363434aa1ffd51bbcf37518":{
      "scriptId":"u68"},
    "c389cfff867e41dd9a788fe94555293b":{
      "scriptId":"u69"},
    "a0c9f2d1e4564e6dae30298dba321e15":{
      "scriptId":"u70"},
    "6122ad8e73e249948b28919f8a9c0bf8":{
      "scriptId":"u71"},
    "946312a4ea204459948bc12cf8520190":{
      "scriptId":"u72"},
    "62159c265c764f8aa98c84c4b01ee13f":{
      "scriptId":"u73"},
    "ff5ff889a0484ac99cade352e895e88f":{
      "scriptId":"u74"},
    "3f80e81f5db641c88653c8e660f618d3":{
      "scriptId":"u75"},
    "352289d9f10d41bd8267152c046105f3":{
      "scriptId":"u76"},
    "694e25a960f04e889e5431864647834c":{
      "scriptId":"u77"},
    "408c238065a44b7c9f05091be5a5d2f9":{
      "scriptId":"u78"},
    "f86168c56ee74a598b738ccc5f87304b":{
      "scriptId":"u79"},
    "b303f005fbbe4b9ea775d5655c756e1b":{
      "scriptId":"u80"},
    "20837be443444959bff9b5337a9964ae":{
      "scriptId":"u81"},
    "2231c03d95714df090addfe3ee70d53e":{
      "scriptId":"u82"},
    "7b7dcdf8f5654b6499778b6f22287a9a":{
      "scriptId":"u83"},
    "c48de03d00bf4056b4e61e8a7abe0e72":{
      "scriptId":"u84"},
    "5a179cff963a453aa5f7a553f2f79c25":{
      "scriptId":"u85"},
    "d36b887eab7148b582c80ce3d316aa24":{
      "scriptId":"u86"},
    "99de3c358579431ea86da57699b4c1ac":{
      "scriptId":"u87"},
    "4411f8de2de448f5bb75ca61431bd35e":{
      "scriptId":"u88"},
    "4ec8fd1c906644ff8bdcfaa4ec1f5ce9":{
      "scriptId":"u89"},
    "7ce87abdbf834cbe966d7f6bd2584f0e":{
      "scriptId":"u90"},
    "68c00f2b6902493c928914a848aaa791":{
      "scriptId":"u91"},
    "3d8d6164b5b844a5b436abf62931b386":{
      "scriptId":"u92"},
    "7385e63590a44ebb8119573cf2b7c46a":{
      "scriptId":"u93"},
    "48e45ed3b7ca451faa535489cdcffa6a":{
      "scriptId":"u94"},
    "43d5d619eae44cee93b9c5eb373f3cb2":{
      "scriptId":"u95"},
    "a4ee72283b8b46b9bf1e04d105a4556a":{
      "scriptId":"u96"},
    "85a1738b4026428bb0f18e21ca836b52":{
      "scriptId":"u97"},
    "df37f18f551f48dcae5d8dab9f047180":{
      "scriptId":"u98"},
    "1a3f54ec02ff4c23869179e609de6d7c":{
      "scriptId":"u99"},
    "409fb0042ee34a9ca1328ff02a2697d4":{
      "scriptId":"u100"},
    "610b1cc4f9e649d3a0ce74a32feb48e9":{
      "scriptId":"u101"},
    "3e754adfaa0e4ab394d122c3594cf985":{
      "scriptId":"u102"},
    "acd8795086a1437ca8b4e6769e174c61":{
      "scriptId":"u103"},
    "5a03c4081be54772ba478a9ad09b74f8":{
      "scriptId":"u104"},
    "60e1ff7a53454c158b011b1f09c5847f":{
      "scriptId":"u105"},
    "95ebcf35c00d4685a07f820c7fa7dfad":{
      "scriptId":"u106"},
    "cd8c228b1ac54b0a8ff470e268575ad1":{
      "scriptId":"u107"},
    "d994d469142d4b45a4ccd1621068f043":{
      "scriptId":"u108"},
    "27a490ef18914b5fa6d6660d7fdca8a6":{
      "scriptId":"u109"},
    "b4302d5e8f364cf3a881065a2834a1d7":{
      "scriptId":"u110"},
    "2e1079b9ba6c45acacd0e3048373905c":{
      "scriptId":"u111"},
    "7f09c6ff77624ad9af4d7ed39d2ac7e1":{
      "scriptId":"u112"},
    "8796ca829ac746b3b8439b2692eb3c1c":{
      "scriptId":"u113"},
    "c435706701c744158e80904c0f2679df":{
      "scriptId":"u114"},
    "5cab3bd420d44faaac10bb8ddff1948b":{
      "scriptId":"u115"},
    "436f0beed9e14e3d9a3db69046518e87":{
      "scriptId":"u116"},
    "f78189e960e54537899bcfb89f0875b0":{
      "scriptId":"u117"},
    "71fa6a54e5d346b2907b59cdc7cc0b26":{
      "scriptId":"u118"},
    "c1e0e8163fd940428b2585359a777bd2":{
      "scriptId":"u119"},
    "44409bce5ebb495ba6c742049dbfdfb2":{
      "scriptId":"u120"},
    "92120f3330f244928bb4e04120b8f10d":{
      "scriptId":"u121"},
    "c93a4195ea754623b38bd2879f74693a":{
      "scriptId":"u122"},
    "0b0b18a51c4e4e3a883d2c18920fa6cc":{
      "scriptId":"u123"},
    "fee1784081ba49918861263a5a01d74a":{
      "scriptId":"u124"},
    "8c6a9f64a7a44d3a9d68c5c725d34743":{
      "scriptId":"u125"},
    "870dec2f1c484f3baf787b786361e4b3":{
      "scriptId":"u126"}}});