$axure.loadCurrentPage({
  "url":"order_list.html",
  "generationDate":new Date(1594096788859.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/order_list/bg.jpg",
    "width":414,
    "height":736},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"cbfed7b2d37f4928a539d7ac5dda8c03",
    "type":"Axure:Page",
    "name":"order_list",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e98f68ff17d742ee9d7e3a407452ce46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":286,
              "y":78},
            "size":{
              "width":26,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e077dbb880ef4c4cb1eabafdc56d4c81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":286,
                  "y":78},
                "size":{
                  "width":26,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 shopcart",
                      "target":{
                        "targetType":"page",
                        "url":"shopcart.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u2.png"}},
{
          "id":"ae594c60a5f44641868bc651f6751449",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":79},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"00f0fc0a302c42e584ca27636a76d75d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":414,
              "height":622}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214ececb444e4877a8fa2db9843b4989",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":414,
                  "height":622}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/order_list/u3.png"}},
{
          "id":"cca88f52732e490c86505be03e1fb720",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":414,
              "height":304}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 order_details",
                      "target":{
                        "targetType":"page",
                        "url":"order_details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c90c0d2ff0884e38b51dc4898c0f03a1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":442},
            "size":{
              "width":414,
              "height":158}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 order_details",
                      "target":{
                        "targetType":"page",
                        "url":"order_details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5150a06a5aab493197b6756724da4a88",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":624},
            "size":{
              "width":414,
              "height":106}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 order_details",
                      "target":{
                        "targetType":"page",
                        "url":"order_details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b76bbc897b434cbe90627a456172e13d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":31},
            "size":{
              "width":50,
              "height":19}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "e98f68ff17d742ee9d7e3a407452ce46":{
      "scriptId":"u0"},
    "e077dbb880ef4c4cb1eabafdc56d4c81":{
      "scriptId":"u1"},
    "ae594c60a5f44641868bc651f6751449":{
      "scriptId":"u2"},
    "00f0fc0a302c42e584ca27636a76d75d":{
      "scriptId":"u3"},
    "214ececb444e4877a8fa2db9843b4989":{
      "scriptId":"u4"},
    "cca88f52732e490c86505be03e1fb720":{
      "scriptId":"u5"},
    "c90c0d2ff0884e38b51dc4898c0f03a1":{
      "scriptId":"u6"},
    "5150a06a5aab493197b6756724da4a88":{
      "scriptId":"u7"},
    "b76bbc897b434cbe90627a456172e13d":{
      "scriptId":"u8"}}});