$axure.loadCurrentPage({
  "url":"pay_successful.html",
  "generationDate":new Date(1594096576781.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78da4402fb7044f188cc4564b77f0a88",
    "type":"Axure:Page",
    "name":"pay_successful",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"904d8b493a3d434a9f3ea32efef43b52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":414,
              "height":829}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26aa87ee0f9f4b0db17c69bc1bbe1539",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":414,
                  "height":829}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pay_successful/u0.jpg"}},
{
          "id":"f516231d10fb44b8adc2d19dc343f024",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":125},
            "size":{
              "width":36,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 orderlist",
                      "target":{
                        "targetType":"page",
                        "url":"orderlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f06f76366cf8473896fd236c30be9511",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":647},
            "size":{
              "width":330,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 orderlist",
                      "target":{
                        "targetType":"page",
                        "url":"orderlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0cb57516ffde442793522c875fa49183",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":70},
            "size":{
              "width":40,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 pay",
                      "target":{
                        "targetType":"page",
                        "url":"pay.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4945c3a4ff954e329136fbf7859f022c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 index",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7a72336ebab8480cb84ea1a679bebbe0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":583},
            "size":{
              "width":332,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 dealer_navigation",
                      "target":{
                        "targetType":"page",
                        "url":"dealer_navigation.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "904d8b493a3d434a9f3ea32efef43b52":{
      "scriptId":"u0"},
    "26aa87ee0f9f4b0db17c69bc1bbe1539":{
      "scriptId":"u1"},
    "f516231d10fb44b8adc2d19dc343f024":{
      "scriptId":"u2"},
    "f06f76366cf8473896fd236c30be9511":{
      "scriptId":"u3"},
    "0cb57516ffde442793522c875fa49183":{
      "scriptId":"u4"},
    "4945c3a4ff954e329136fbf7859f022c":{
      "scriptId":"u5"},
    "7a72336ebab8480cb84ea1a679bebbe0":{
      "scriptId":"u6"}}});