$axure.loadCurrentPage({
  "url":"color_picker3_internal.html",
  "generationDate":new Date(1594040141879.97),
  "isCanvasEnabled":false,
  "variables":["uploadResumePopup",
"companyCombination",
"resumeCandidate",
"companyCandidate",
"uploadCompanyPopup"],
  "page":{
    "packageId":"5949380f730343238352feeca0a1e24d",
    "type":"Axure:Page",
    "name":"color_picker3_internal",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2bbf08b1405e430ca640fe11ecda3e17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":259,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"484ccd7c345646b0a261fe5eecd59ff8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":259,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/color_picker3_internal/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2bbf08b1405e430ca640fe11ecda3e17":{
      "scriptId":"u0"},
    "484ccd7c345646b0a261fe5eecd59ff8":{
      "scriptId":"u1"}}});